# Title
[]()

In [1]:
# from pandas import json_normalize  
import tabula
import pandas as pd
import sys
sys.path.append(r"C:\Users\silvh\OneDrive\lighthouse\custom_python")
sys.path.append(r"C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\online-PT-social-media-NLP\src")
from silvhua import *
# from datetime import datetime
# import json
# from plotly.subplots import make_subplots
# import requests

import warnings
warnings.simplefilter("ignore", category=FutureWarning)

In [4]:
# path = r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\y BC health data'
df1 = tabula.read_pdf("F22-1445 Records_Part1.pdf", pages='all')

Got stderr: Mar. 23, 2023 7:25:50 P.M. org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Mar. 23, 2023 7:25:50 P.M. org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Mar. 23, 2023 7:25:52 P.M. org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 357 fonts

In [8]:
df1[0]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_\rcluster_con\rfirmed_pu\rblic_health,date_\rcluster_no\r_longer_ac\rtive,earliest_repor\rted_cases,latest_repo\rrted_cases,workplace_classi\rfication,...,workplace_st\ratus,closure_\ry_n,closed_\rby_ord\rer,voluntary_\rclosure,closure_da\rte,partially_c\rosed,open,days_\rsince_\rlast_c\rase,cluster_\rconfirm\red_epid\rate,cluster_cl\rosed_epi\rdate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
6,7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
11,12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
12,13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
13,14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
14,15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
15,16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN

In [12]:
len(df1)

124

In [24]:
df1[3]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_\rcluster_con\rfirmed_pu\rblic_health,date_\rcluster_no\r_longer_ac\rtive,earliest_repor\rted_cases,latest_repo\rrted_cases,workplace_classi\rfication,...,workplace_st\ratus,closure_\ry_n,closed_\rby_ord\rer,voluntary_\rclosure,closure_da\rte,partially_c\rosed,open,days_\rsince_\rlast_c\rase,cluster_\rconfirm\red_epid\rate,cluster_cl\rosed_epi\rdate
0,49,FHA,s.22(1),SURREY,4/5/2021,4/15/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,...,No,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN
1,50,NHA,Unknown,4/5/2021,4/13/2021,NaN,NaN,Manufacturing/I\rndustry,NaN,3,...,No,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN
2,51,NHA,Unknown,4/5/2021,4/20/2021,NaN,NaN,Shelter/SRO/Con\rgregate Housing,NaN,7,...,No,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN
3,52,FHA,SURREY,4/6/2021,4/16/2021,NaN,NaN,Retail,5,5,...,Yes,Unknown,4/8/2021,No,No,NaN,14-2021,14-2021,NaN,NaN
4,53,FHA,LANGLEY,4/6/2021,4/20/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
5,54,FHA,ABBOTSFORD,4/6/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/6/2021,No,No,NaN,14-2021,14-2021,NaN,NaN
6,55,FHA,BURNABY,4/6/2021,4/24/2021,NaN,NaN,Retail,6,6,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
7,56,FHA,DELTA,4/6/2021,4/14/2021,NaN,NaN,Manufacturing/I\rndustry,3,3,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
8,57,FHA,DELTA,4/6/2021,4/21/2021,NaN,NaN,Retail,4,4,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
9,58,FHA,LANGLEY,4/6/2021,4/30/2021,NaN,NaN,Manufacturing/I\rndustry,5,5,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
10,59,FHA,NEW\rWESTMINSTER,4/6/2021,4/14/2021,NaN,NaN,Personal Care,4,4,...,Yes,Unknown,4/9/2021,No,No,NaN,14-2021,14-2021,NaN,NaN
11,60,FHA,PITT\rMEADOWS,4/6/2021,4/6/2021,NaN,NaN,Office,5,5,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
12,61,FHA,PORT MOODY,4/6/2021,4/15/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/8/2021,No,No,NaN,14-2021,14-2021,NaN,NaN
13,62,FHA,SURREY,4/6/2021,4/16/2021,NaN,NaN,Retail,3,3,...,Yes,Unknown,4/7/2021,No,No,NaN,14-2021,14-2021,NaN,NaN
14,63,FHA,SURREY,4/6/2021,4/16/2021,NaN,NaN,Food Processing,5,5,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN

# `parse_pdf` function

In [43]:
from tabula import read_pdf
def parse_pdf(filenames, filepath=None, pages='all'):
    """
    Create dataframe from a PDF file using 
    """
    if type(filenames) != list:
        filenames = [filenames]
    dfs_list = []
    for filename in filenames:
        try:
            filename = f'{filepath}/'.replace('\\','/')+filename if filepath else filename
            df_list = read_pdf(filename, pages=pages)
            dfs_list.append(pd.concat(df_list))
        except:
            return pd.concat(dfs_list)
    df = pd.concat(dfs_list).reset_index(drop=True)
    df = df.set_index('Unnamed: 0')
    df.index.name = None
    return df

df = parse_pdf("F22-1445 Records_Part1.pdf", pages=[1, 2])
df

,HA,workplace_name,workplace_address,city,date_\rcluster_con\rfirmed_pu\rblic_health,date_\rcluster_no\r_longer_ac\rtive,earliest_repor\rted_cases,latest_repo\rrted_cases,workplace_classi\rfication,cases_when_c\rluster_confirm\red,...,workplace_st\ratus,closure_\ry_n,closed_\rby_ord\rer,voluntary_\rclosure,closure_da\rte,partially_c\rosed,open,days_\rsince_\rlast_c\rase,cluster_\rconfirm\red_epid\rate,cluster_cl\rosed_epi\rdate
1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,Closed,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,Closed,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,Closed,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,Closed,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,Closed,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,Closed,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,Closed,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,Closed,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
17,FHA,s.22(1),LANGLEY,4/2/2021,4/24/2021,NaN,NaN,Personal Care,4,4,...,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN
18,FHA,BURNABY,4/2/2021,4/16/2021,NaN,NaN,Food Processing,6,6,Closed,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
19,FHA,COQUITLAM,4/2/2021,4/7/2021,NaN,NaN,Other,5,5,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
20,FHA,DELTA,4/2/2021,4/10/2021,NaN,NaN,Office,3,3,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
21,FHA,LANGLEY,4/2/2021,4/5/2021,NaN,NaN,Retail,4,4,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
22,FHA,LANGLEY,4/2/2021,4/17/2021,NaN,NaN,Farm/Agriculture,5,5,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
23,FHA,PORT\rCOQUITLAM,4/2/2021,4/18/2021,NaN,NaN,First Responder,3,3,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
24,FHA,SURREY,4/2/2021,4/18/2021,NaN,NaN,Retail,5,5,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
25,FHA,SURREY,4/2/2021,4/28/2021,NaN,NaN,Manufacturing/I\rndustry,4,4,NaN,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
26,FHA,BURNABY,4/4/2021,4/22/2021,NaN,NaN,Gym/Fitness,6,6,Closed,...,Yes,Unknown,4/2/2021,No,No,NaN,14-2021,13-2021,NaN,NaN
27,FHA,PITT\rMEADOWS,4/4/2021,5/3/2021,NaN,NaN,Farm/Agriculture,8,8,NaN,...,No,Unknown,NaN,No,No,NaN,14-2021,NaN,NaN,NaN
28,FHA,SURREY,4/4/2021,4/10/2021,NaN,NaN,Office,8,8,Closed,...,Yes,Unknown,4/4/2021,No,No,NaN,14-2021,14-2021,NaN,NaN
29,NHA,Unknown,4/4/2021,4/26/2021,NaN,NaN,Shelter/SRO/Con\rgregate Housing,3,6,"Open (if\ropen, reason\rfor non-\rclosure)",...,No,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN
30,NHA,Unknown,4/4/2021,4/26/2021,NaN,NaN,Shelter/SRO/Con\rgregate Housing,NaN,11,"Open (if\ropen, reason\rfor non-\rclosure)",...,No,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN
31,NHA,Unknown,4/4/2021,4/26/2021,NaN,NaN,Shelter/SRO/Con\rgregate Housing,NaN,5,"Open (if\ropen, reason\rfor non-\rclosure)",...,No,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN

## Iteration 2

In [71]:
from tabula import read_pdf
def parse_pdf(pdf_filenames, filepath=None, pages='all', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    for filename in pdf_filenames:
        print(filename, end='...')
        try:
            filename = f'{filepath}/'.replace('\\','/')+filename if filepath else filename
            df_list = read_pdf(filename, pages=pages)
            dfs_list.append(pd.concat(df_list))
        except:
            return pd.concat(dfs_list)
        print('Done')
    df = pd.concat(dfs_list).reset_index(drop=True)
    df = df.set_index('Unnamed: 0')
    df.index.name = None

    

    return df

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
df = parse_pdf(filenames, pages=[1, 2])
df
# Too many extra columns added due to differences in column width

Extracting the following files:
F22-1445 Records_Part1.pdf...Done
F22-1445 Records_Part2.pdf...Done

,HA,workplace_name,workplace_address,city,date_\rcluster_con\rfirmed_pu\rblic_health,date_\rcluster_no\r_longer_ac\rtive,earliest_repor\rted_cases,latest_repo\rrted_cases,workplace_classi\rfication,cases_when_c\rluster_confirm\red,...,latest_repor\rted_cases,workplace_clas\rsification,cases_\rwhen_c\rluster_\rconfirm\red,workplace_s\rtatus,closed_by\r_order,partially_\rclosed,days_s\rince_la\rst_cas\re,active_clu\rsters,cluster_c\ronfirmed\r_epidate,cluster_cl\rosed_epid\rate
1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4.0,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12.0,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5.0,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,FHA,NaN,LANGLEY,4/19/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,Manufacturing\r/Industry,4,4.0,No,Unknown,No,No,16-2021,NaN,NaN
213,FHA,NaN,LANGLEY,4/19/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,Manufacturing\r/Industry,3,3.0,Yes,Unknown,No,No,16-2021,16-2021,NaN
214,FHA,NaN,BURNABY,4/19/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,Office,3,3.0,No,Unknown,No,No,16-2021,NaN,NaN
215,FHA,NaN,LANGLEY,4/19/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,Food\rProcessing,7,7.0,No,Unknown,No,No,16-2021,NaN,NaN
216,FHA,NaN,DELTA,4/19/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,Farm/Agricultu\rre,5,5.0,No,Unknown,No,No,16-2021,NaN,NaN

In [72]:
df.head()

,HA,workplace_name,workplace_address,city,date_\rcluster_con\rfirmed_pu\rblic_health,date_\rcluster_no\r_longer_ac\rtive,earliest_repor\rted_cases,latest_repo\rrted_cases,workplace_classi\rfication,cases_when_c\rluster_confirm\red,...,latest_repor\rted_cases,workplace_clas\rsification,cases_\rwhen_c\rluster_\rconfirm\red,workplace_s\rtatus,closed_by\r_order,partially_\rclosed,days_s\rince_la\rst_cas\re,active_clu\rsters,cluster_c\ronfirmed\r_epidate,cluster_cl\rosed_epid\rate
1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4.0,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12.0,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5.0,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
filter = df['workplace_name'] == 's.22(1)'
# filter = df['workplace_name'] == 'SURREY'
df[filter]

,HA,workplace_name,workplace_address,city,date_\rcluster_con\rfirmed_pu\rblic_health,date_\rcluster_no\r_longer_ac\rtive,earliest_repor\rted_cases,latest_repo\rrted_cases,workplace_classi\rfication,cases_when_c\rluster_confirm\red,...,latest_repor\rted_cases,workplace_clas\rsification,cases_\rwhen_c\rluster_\rconfirm\red,workplace_s\rtatus,closed_by\r_order,partially_\rclosed,days_s\rince_la\rst_cas\re,active_clu\rsters,cluster_c\ronfirmed\r_epidate,cluster_cl\rosed_epid\rate
17,FHA,s.22(1),LANGLEY,4/2/2021,4/24/2021,NaN,NaN,Personal Care,4.0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df.loc[17]

HA                                                      FHA
workplace_name                                      s.22(1)
workplace_address                                   LANGLEY
city                                               4/2/2021
date_\rcluster_con\rfirmed_pu\rblic_health        4/24/2021
date_\rcluster_no\r_longer_ac\rtive                     NaN
earliest_repor\rted_cases                               NaN
latest_repo\rrted_cases                       Personal Care
workplace_classi\rfication                              4.0
cases_when_c\rluster_confirm\red                          4
total_c\rases                                           NaN
workplace_st\ratus                                       No
closure_\ry_n                                            No
closed_\rby_ord\rer                                 Unknown
voluntary_\rclosure                                     NaN
closure_da\rte                                           No
partially_c\rosed                                        No
open                                                    NaN
days_\rsince_\rlast_c\rase                          13-2021
cluster_\rconfirm\red_epid\rate                         NaN
cluster_cl\rosed_epi\rdate                              NaN
date_clust\rer_confirm\red_public_\rhealth              NaN
date_clust\rer_no_long\rer_active                       NaN
earliest_re\rported_cas\res                             NaN
latest_repor\rted_cases                                 NaN
workplace_clas\rsification                              NaN
cases_\rwhen_c\rluster_\rconfirm\red                    NaN
workplace_s\rtatus                                      NaN
closed_by\r_order                                       NaN
partially_\rclosed                                      NaN
days_s\rince_la\rst_cas\re                              NaN
active_clu\rsters                                       NaN
cluster_c\ronfirmed\r_epidate                           NaN
cluster_cl\rosed_epid\rate                              NaN
Name: 17, dtype: object

In [52]:
def delete_cell(df):

hellothere

## Iteration 3
Need to change column names to avoid extra columns being added due to different column widths between documents. 
* Part 1 has 21 columns.
* Part 2 has 22 columns.
* Part 7 has 23 columns

In [97]:
from tabula import read_pdf
import re
def parse_pdf(pdf_filenames, filepath=None, pages='all', text_to_remove='s.22(1)', 
    column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    for filename in pdf_filenames:
        print(filename, end='...')
        try:
            filename = f'{filepath}/'.replace('\\','/')+filename if filepath else filename
            df_list = read_pdf(filename, pages=pages)
            df_temp = pd.concat(df_list)
            df_temp.columns = df_temp.columns.str.replace('\r', '')
            df_temp.columns = df_temp.columns.str.replace('cosed', 'closed')
            # df[re.sub(r'.*(Part[1-9]).pdf', r'\1', filename)] = df_temp.columns.to_list()
            dfs_list.append(df_temp)
        except:
            return pd.concat(dfs_list)
        print('Done')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[f'part{i}'] = unique_columns
        print(f'Columns unique to part{i}: {unique_columns if len(unique_columns)>0 else "none"}')
    df = pd.concat(dfs_list).reset_index(drop=True)
    df = df.set_index('Unnamed: 0')
    df.index.name = None
    rows_to_shift = df[df['workplace_name'] == text_to_remove].index
    # df_shifted = df.loc[rows_to_shift].drop(columns=[column_to_adjust])
    # df_shifted.columns

    try:
        original_col_sequence = df.columns.tolist()
        index = original_col_sequence.index(column_to_adjust)
        adjusted_col_sequence = original_col_sequence.append(original_col_sequence.pop(index))
        df_extra_text_removed = df.loc[rows_to_shift]
        df_corrected = pd.concat([
            df.loc
        ])
    except ValueError:
        pass  # the value is not in the list
    return df, unique_cols_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
df3, unique_cols = parse_pdf(filenames, pages=[1, 2])
df3

Extracting the following files:
F22-1445 Records_Part1.pdf...Done
F22-1445 Records_Part2.pdf...Done
Columns unique to part0: none
Columns unique to part1: {'active_clusters'}

,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,cases_when_cluster_confirmed,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,active_clusters
1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,NaN,...,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN,NaN
2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,NaN,...,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN,NaN
3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,Closed,...,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,Closed,...,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,Closed,...,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,FHA,NaN,LANGLEY,4/19/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,4,4,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
213,FHA,NaN,LANGLEY,4/19/2021,5/3/2021,NaN,NaN,Manufacturing\r/Industry,3,3,...,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,NaN,16-2021
214,FHA,NaN,BURNABY,4/19/2021,5/1/2021,NaN,NaN,Office,3,3,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
215,FHA,NaN,LANGLEY,4/19/2021,5/10/2021,NaN,NaN,Food\rProcessing,7,7,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
216,FHA,NaN,DELTA,4/19/2021,4/26/2021,NaN,NaN,Farm/Agricultu\rre,5,5,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021

In [98]:
filter = df3['workplace_name'] == 's.22(1)'
df3[filter]

,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,cases_when_cluster_confirmed,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,active_clusters
17,FHA,s.22(1),LANGLEY,4/2/2021,4/24/2021,NaN,NaN,Personal Care,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN

In [100]:
df3.columns.tolist().index('HA')

0

In [102]:
df3.tail(40)

,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,cases_when_cluster_confirmed,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,active_clusters
30,NHA,Unknown,4/4/2021,4/26/2021,NaN,NaN,Shelter/SRO/Con\rgregate Housing,NaN,11,"Open (if\ropen, reason\rfor non-\rclosure)",...,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN,NaN
31,NHA,Unknown,4/4/2021,4/26/2021,NaN,NaN,Shelter/SRO/Con\rgregate Housing,NaN,5,"Open (if\ropen, reason\rfor non-\rclosure)",...,No,NaN,Unknown,No,NaN,14-2021,NaN,NaN,NaN,NaN
179,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,3,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021,No
180,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,11,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,15-2021
181,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,NaN,15-2021
182,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,4,...,No,No,NaN,Yes,No,NaN,No,NaN,NaN,15-2021
183,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,4,...,No,Yes,NaN,Unknown,No,NaN,No,NaN,NaN,15-2021
184,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,12,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,NaN,15-2021
185,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,13,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,NaN,15-2021
186,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,25,25,...,Yes,Unknown,4/18/2021,No,No,NaN,No,16-2021,NaN,15-2021
187,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,5,5,...,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,NaN,15-2021
188,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,4,4,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,NaN,15-2021
189,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,NaN,3,...,No,No,NaN,Yes,No,NaN,No,NaN,NaN,15-2021
190,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,3,3,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,15-2021
191,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,11,11,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,15-2021
192,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,7,7,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,15-2021
193,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,4,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,16-2021,NaN,15-2021
194,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,4,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,15-2021
195,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,3,...,No,No,NaN,Yes,No,NaN,No,NaN,NaN,15-2021
196,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,4,...,No,No,NaN,No,Yes,NaN,No,NaN,NaN,15-2021
197,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,21,...,Yes,No,4/21/2021,No,No,NaN,No,16-2021,NaN,15-2021
198,FHA,NaN,s.22(1),PORT\rCOQUITLAM,4/17/2021,4/26/2021,NaN,NaN,Transportation,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,No
199,FHA,NaN,BURNABY,4/17/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,4,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,16-2021,NaN,15-2021
200,VCH,NaN,North\rVancouver,4/17/2021,NaN,4/17/2021,5/2/2021,Retail,NaN,3,...,No,No,NaN,No,Yes,NaN,No,NaN,NaN,15-2021
201,VCH,NaN,West\rVancouver,4/17/2021,NaN,4/17/2021,5/14/2021,Maintenance/T\rrades/Construc\rtion,NaN,12,...,Yes,No,4/24/2021,No,No,NaN,No,16-2021,NaN,15-2021
202,NHA,NaN,Unknown,4/17/2021,5/20/2021,NaN,NaN,Health Care\rFacility\r(Acute/LTC),NaN,5,...,No,No,NaN,Unknown,No,NaN,No,NaN,NaN,15-2021
203,FHA,NaN,ABBOTSFORD,4/18/2021,4/18/2021,NaN,NaN,Other,5,5,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
204,FHA,NaN,PORT\rCOQUITLAM,4/18/2021,5/6/2021,NaN,NaN,Gym/Fitness,5,5,...,Yes,Unknown,4/19/2021,No,No,NaN,No,16-2021,NaN,16-2021
205,FHA,NaN,SURREY,4/18/2021,5/5/2021,NaN,NaN,Retail,13,13,...,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,NaN,16-2021
206,FHA,NaN,SURREY,4/18/2021,5/5/2021,NaN,NaN,Gym/Fitness,3,3,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
207,VCH,NaN,North\rVancouver,4/18/2021,NaN,4/18/2021,5/12/2021,School/Daycar\re,NaN,11,...,Yes,No,4/6/2021,No,No,NaN,No,14-2021,NaN,16-2021
208,NHA,NaN,Unknown,4/18/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,3,...,No,Yes,NaN,Unknown,No,NaN,No,NaN,NaN,16-2021
209,FHA,NaN,SURREY,4/19/2021,4/29/2021,NaN,NaN,Office,6,6,...,No,Unknown,4/21/2021,Yes,No,NaN,No,16-2021,NaN,16-2021
210,FHA,NaN,BURNABY,4/19/2021,5/7/2021,NaN,NaN,Office,10,10,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
211,FHA,NaN,SURREY,4/19/2021,5/4/2021,NaN,NaN,Manufacturing\r/Industry,3,3,...,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,NaN,16-2021
212,FHA,NaN,LANGLEY,4/19/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,4,4,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
213,FHA,NaN,LANGLEY,4/19/2021,5/3/2021,NaN,NaN,Manufacturing\r/Industry,3,3,...,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,NaN,16-2021
214,FHA,NaN,BURNABY,4/19/2021,5/1/2021,NaN,NaN,Office,3,3,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
215,FHA,NaN,LANGLEY,4/19/2021,5/10/2021,NaN,NaN,Food\rProcessing,7,7,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021
216,FHA,NaN,DELTA,4/19/2021,4/26/2021,NaN,NaN,Farm/Agricultu\rre,5,5,...,No,Unknown,NaN,No,No,NaN,No,NaN,NaN,16-2021

## Iteration 4: parse each pdf separately because the column alignments vary from doc to doc

In [11]:
from tabula import read_pdf
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    for file in pdf_filenames:
        print(filename, end='...')
        try:
            file = f'{filepath}/'.replace('\\','/')+file if filepath else file
            df_list = read_pdf(file, pages=pages)
            df_temp = pd.concat(df_list)
            df_temp.columns = df_temp.columns.str.replace('\r', '')
            df_temp.columns = df_temp.columns.str.replace('cosed', 'closed')
            df_temp = df_temp.set_index('Unnamed: 0')
            df_temp.index.name = None
            dfs_list.append(df_temp)
        except:
            return pd.concat(dfs_list)
        print('Done')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[f'part{i}'] = unique_columns
        print(f'Columns unique to part{i}: {unique_columns if len(unique_columns)>0 else "none"}')
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
        except:
            print('Unable to save outputs')

    return dfs_list, unique_cols_dict

n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs, unique_cols = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
dfs[2]

Extracting the following files:
pdfs_parsed_to_df_list...Done
pdfs_parsed_to_df_list...Done
pdfs_parsed_to_df_list...Done
pdfs_parsed_to_df_list...Done
pdfs_parsed_to_df_list...Done
pdfs_parsed_to_df_list...Done
pdfs_parsed_to_df_list...Done
Columns unique to part0: {'closed_by_', 'closed_by'}
Columns unique to part1: {'cases_wh', 'date_clust'}
Columns unique to part2: {'closure_y_'}
Columns unique to part3: none
Columns unique to part4: none
Columns unique to part5: {'Unknown', '31-2021', '13-2021', '226', '38-2021', '4/12/2021', 'ANGLEY', 'BURNABY', 's.22(1)', '8/30/2021', '6.1', '9/30/2021', '[2] Notclosed:Insufficient evidenceof recenttransmission', 'Voluntarily closedbyoperator', '154', 'NEWWESTMINSTER', '7', 'Restaurant/Ba', 'CHILLIWACK', '5/10/2021', '4', 'Retail', '32-2021', '7/26/2021', 'Open', '10/2/2021', '893', '9/23/2021', '16-2021', '55', 'Langford', '5/3/2021', 'rail', 'No.5', '4/23/2021', '5/19/2021', '312', '961', '734', '4.1', '5/9/2021', 'NHA', '11/16/2021', 'DELTA', '21-2021', '3.1', '35-2021', '[4] Notclosed:Publicinterest inremainingopen', 'VCH', '496', '10.1', '8/9/2021.1', 'MISSION', 'Hospitality/Se', '8/12/2021', 'IHA', '5/9/2021.1', '139', '25', '5/20/2021', '803', '14-2021', '16-2021.1', '10', '6/7/2021', '8/5/2021', '18-2021', '6', 'Not closed', '620', '6/23/2021', '9/6/2021', '20-2021', 'Restaurant/Bar/Lounge', '8/28/2021', '714', 'Yes.2', '4/8/2021', 'Gym/Fitness', '5/29/2021', '9/25/2021', '10/25/2021.1', 'BBOTSFRD', '4/5/2021.1', '19-2021', '5/7/2021', '123', '8/8/2021', '4/2/2021', '9/17/2021', '15', '4/18/2021', '39-2021', 'School/Daycare', 'Transportation', '11/17/2021', '286', '5.1', '4/21/2021', '8/24/2021', '44-2021', 'Maintenance/Trades/Construction', '652', 'VIHA', '[3] Not', 'Other', '28', 'No.1', '4/10/2021.1', '857', 'SURREY', '43-2021', '4/3/2021', '603', '17-2021', '15-2021', 'Penticton', '25.1', '5/18/2021', '231', '8/30/2021.1', '5/6/2021', '4/23/2021.1', '10/18/2021', '635', '22-2021', '837', 'ABBOTSFORD', 'ictoria', '30-2021', '400', '9/2/2021', '229', '8/12/2021.1', '4/9/2021', '4/5/2021', '5/25/2021', 'Essentialfunction(notclosed)', 'No.3', 'NorthVancouver', 'Managed', '11/6/2021', 'Vernon', '5', '4/15/2021', '4/29/2021', 'Unknown.1', '48-2021', '110', '6/8/2021', '33-2021', '84', '10/25/2021', '413', '17-2021.1', 'Manufacturing/Industry', 'ancouver', '4/11/2021.1', '523', 'Closed', '7.1', '4/25/2021', 'Personal Care', 'Open (ifopen,reason fornon-closure)', '42-2021', '4/28/2021', '273', '4/10/2021', '3', '4/20/2021', '699', '4/11/2021', '[1] Closed', '8', 'Farm/Agriculture', 'Kelowna', '12/4/2021', 'West', '11/1/2021', '468', '6/3/2021', '34-2021', '18-2021.1', '4/22/2021', '8/17/2021', 'FoodProcessing', '243', '4/20/2021.1', '[3] Notclosed:Alternatecontrolmeasures', '9/23/2021.1', '0', 'Yes', 'No.2', '213', '5/11/2021', 'Office', 'No', 'Yes.1', 'No.4', '4/25/2021.1', '13-2021.1', 'Armstrong', '4/19/2021', 'URREY', '8/6/2021', 'School/Daycar', 'Castlegar', 'COQUITLAM', '389', '8/25/2021', 'uncan', '5/7/2021.1', '8/9/2021', 'Maintenance/', '66', '4/7/2021', '20-2021.1', '9/3/2021', '346', '687', '184', '785', '258', '14-2021.1', '8/5/2021.1', 'FHA'}
Columns unique to part6: none
File saved:  C:/Users/silvh/OneDrive/lighthouse/portfolio-projects/BC-Covid-workplace-closures/data/interim/pdfs_parsed_to_df_list.sav
Time completed: 2023-03-24 20:27:46.315841

,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,cases_when_cluster_confirmed,...,Unnamed: 22,Unnamed: 23,date_cluster_no_longer_active,latest_reported_cases,workplace_classification,cases_when_cluster_confirmed,workplace_status,closed_by_order,active_clusters,cluster_closed_epidate
1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,FHA,SURREY,4/14/2021,4/27/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,4,Closed,Yes,4/16/2021,15-2021,NaN
175,FHA,SURREY,4/14/2021,4/24/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,5,Closed,Yes,4/14/2021,15-2021,NaN
176,FHA,SURREY,4/14/2021,4/24/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,5,Closed,Yes,4/15/2021,15-2021,NaN
177,FHA,BURNABY,4/14/2021,4/27/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7.0,7,NaN,No,NaN,NaN,NaN
178,FHA,PORT\rCOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,5,Closed,Yes,4/18/2021,16-2021,NaN

In [17]:
dfs[1].columns

Index(['HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed', 'open',
       'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'cases_', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'workplacename',
       'workplaceaddress', 'date_cluster_confirmed_public_health',
       'date_cluster_no_longer_active', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'closed_by_order', 'days_since_last_case', 'active_clusters',
       'cluster_confirmed_epidate', 'cluster_closed_epidate',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'cases_when_cluster_confirmed', 'total_cases', 'workplace_status',
       'closure_y_n', 'closed_by_order', 'closure_date', 'partially_closed',
       'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'cases_when_cluster_confirmed', 'total_cases',
       'days_since_last_case', 'active_clusters', 'date_clust', 'cases_wh'],
      dtype='object')

In [13]:
dfs[2]

,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,cases_when_cluster_confirmed,...,latest_reported_cases,workplace_classification,closure_y_n,closed_by_order,closure_date,unknown_closure_type,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
1.0,FHA,s.22(1),LANGLEY,4/1/2021,4/24/2021,NaN,NaN,Personal\rCare,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.0,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,FHA,COQUITLA\rM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.0,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agricu\rlture,50,50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.0,FHA,LANGLEY,4/1/2021,6/13/2021,NaN,NaN,Warehouse,31,31,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113.0,FHA,SURREY,NaN,4/26/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,4,4,Unknown,NaN,No,NaN,14-2021,NaN,NaN,NaN
114.0,FHA,SURREY,NaN,4/21/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,4,4,Unknown,NaN,No,NaN,14-2021,NaN,NaN,NaN
115.0,FHA,SURREY,NaN,4/23/2021,NaN,NaN,NaN,NaN,NaN,[1] Closed,...,6,6,Unknown,4/12/2021,No,NaN,14-2021,15-2021,NaN,NaN
116.0,FHA,SURREY,NaN,5/29/2021,NaN,NaN,NaN,NaN,NaN,NaN,...,11,11,Unknown,NaN,No,NaN,14-2021,NaN,NaN,NaN
117.0,VCH,Vancouver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not a\rworksite,...,NaN,5,No,NaN,No,NaN,14-2021,NaN,NaN,NaN

In [14]:
dfs[5]

,Unnamed: 1,s.22(1),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,closure_date,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,workplacename,workplaceaddress
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transportatio,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14.0,FHA,NaN,DELTA,4/1/2021,4/6/2021,NaN,NaN,n,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,Yes,123,No,35-2021,NaN,NaN,NaN,NaN,NaN
734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,No,NaN,No,35-2021,NaN,NaN,NaN,NaN,NaN
735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,Yes,93,No,35-2021,NaN,NaN,NaN,NaN,NaN
736.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,Yes,123,No,35-2021,NaN,NaN,NaN,NaN,NaN
737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,No,NaN,No,35-2021,NaN,NaN,NaN,NaN,NaN

## Iteration 5

In [26]:
from tabula import read_pdf
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    for file in pdf_filenames:
        print(file, end='...')
        try:
            file = f'{filepath}/'.replace('\\','/')+file if filepath else file
            df_list = read_pdf(file, pages=pages)
            df_temp = pd.concat(df_list)
            # df_temp.columns = df_temp.columns.str.replace(r'Unnamed: [\d*]', 'index', regex=True)
            df_temp.columns = df_temp.columns.str.replace('\r', '')
            df_temp.columns = df_temp.columns.str.replace('cosed', 'closed')
            # df_temp = df_temp.set_index('index')
            # df_temp.index.name = None
            dfs_list.append(df_temp)
        except:
            return dfs_list
        print('Done')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[f'part{i+1}'] = unique_columns
        print(f'Columns unique to part{i+1}: {unique_columns if len(unique_columns)>0 else "none"}')
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
        except:
            print('Unable to save outputs')

    return dfs_list, unique_cols_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs5, unique_cols5 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs5[0]

Extracting the following files:
F22-1445 Records_Part1.pdf...Done
F22-1445 Records_Part2.pdf...Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters', 'cases_', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 2', 'Unnamed: 10', 'Unnamed: 19', 'Unnamed: 11', 'Unnamed: 21', 'Unnamed: 17', 'Unnamed: 20', 'Unnamed: 18', 'Unnamed: 14', 'Unnamed: 6', 'Unnamed: 16', 'Unnamed: 7', 'Unnamed: 12', 'Unnamed: 9', 'Unnamed: 13', 'Unnamed: 15', 'Unnamed: 3', 'Unnamed: 1', 'Unnamed: 8'}

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
6,7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
11,12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
12,13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
13,14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
14,15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
15,16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
0,150,FHA,NaN,.22(1),BBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agriculture,...,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021
1,151,FHA,NaN,URNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,7,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
2,152,FHA,NaN,ELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,6,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
3,153,FHA,NaN,ELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
4,154,FHA,NaN,ORT\rOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
5,155,FHA,NaN,ORT\rOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
6,156,FHA,NaN,URREY,4/14/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
7,157,FHA,NaN,URREY,4/14/2021,4/27/2021,NaN,NaN,Retail,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
8,158,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021,NaN
9,159,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Retail,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
10,160,NHA,NaN,nknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,3,...,Yes,No,Yes,NaN,Unknown,No,NaN,15-2021,NaN,NaN
11,161,FHA,NaN,URNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing/I\rndustry,25,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
12,162,FHA,NaN,URNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
13,163,FHA,NaN,ANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
14,164,FHA,NaN,ANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/17/2021,No,No,NaN,15-2021,15-2021,NaN
15,165,FHA,NaN,URREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
16,166,FHA,NaN,URNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN

In [30]:
dfs5[1]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [32]:
dfs5[1]['Unnamed: 0']

0     179.0
1     180.0
2     181.0
3     182.0
4     183.0
      ...
47      NaN
48    358.0
49      NaN
50      NaN
51    359.0
Name: Unnamed: 0, Length: 71, dtype: float64

In [35]:
dfs5[1].loc[50]

Unnamed: 0                                         NaN
HA                                                 NaN
workplace_name                                     NaN
workplace_address                                  NaN
city                                               NaN
date_cluster_confirmed_public_health               NaN
date_cluster_no_longer_active                      NaN
earliest_reported_cases                            NaN
latest_reported_cases                              NaN
workplace_classification                           NaN
cases_when_cluster_confirmed                       NaN
total_cases                                        NaN
workplace_status                                   NaN
closure_y_n                                        NaN
closed_by_order                                    NaN
voluntary_closure                                  NaN
closure_date                                       NaN
partially_closed                                   NaN
open                                               NaN
days_since_last_case                               NaN
active_clusters                                    NaN
cluster_confirmed_epidate                          NaN
cluster_closed_epidate                             NaN
Unnamed: 1                                         NaN
Unnamed: 2                                         NaN
Unnamed: 3                                         NaN
Unnamed: 4                                         NaN
Unnamed: 5                                         NaN
Unnamed: 6                                         NaN
Unnamed: 7                                         NaN
Unnamed: 8                                         NaN
Unnamed: 9                              rades/Construc
cases_                                             NaN
Unnamed: 10                                        NaN
Unnamed: 11                                        NaN
Unnamed: 12                                        NaN
Unnamed: 13                                        NaN
Unnamed: 14                                        NaN
Unnamed: 15                                        NaN
Unnamed: 16                                        NaN
Unnamed: 17                                        NaN
Unnamed: 18                                        NaN
Unnamed: 19                                        NaN
Unnamed: 20                                        NaN
Unnamed: 21                                        NaN
Name: 50, dtype: object

In [38]:
n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(2,n_docs+1)]
dfs5, unique_cols5 = parse_pdf(filenames, pages='10', filename=None)
dfs5[0]

Extracting the following files:
F22-1445 Records_Part2.pdf...Done
Columns unique to part1: {'Unnamed: 17', 'Unnamed: 20', 'Unnamed: 18', 'Unnamed: 4', 'cases_', 'Unnamed: 14', 'Unnamed: 6', 'Unnamed: 16', 'Unnamed: 5', 'Unnamed: 7', 'Unnamed: 2', 'Unnamed: 12', 'Unnamed: 10', 'Unnamed: 19', 'Unnamed: 11', 'Unnamed: 9', 'Unnamed: 13', 'Unnamed: 15', 'Unnamed: 0', 'Unnamed: 3', 'Unnamed: 21', 'Unnamed: 1', 'Unnamed: 8'}

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
2,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,latest_repor,workplace_clas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
3,NaN,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
4,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
25,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
32,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [39]:
dfs5, unique_cols5 = parse_pdf(filenames, pages='1', filename=None)
dfs5[0]

Extracting the following files:
F22-1445 Records_Part2.pdf...Done
Columns unique to part1: {'HA', 'active_clusters', 'cluster_closed_epidate', 'closure_date', 'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active', 'earliest_reported_cases', 'partially_closed', 'workplace_name', 'total_cases', 'days_since_last_case', 'cluster_confirmed_epidate', 'open', 'workplace_address', 'city', 'Unnamed: 0', 'latest_reported_cases', 'cases_when_cluster_confirmed', 'closed_by_order', 'voluntary_closure', 'workplace_status', 'closure_y_n', 'workplace_classification'}

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
5,184,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
6,185,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
7,186,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,25,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
8,187,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,5,...,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021,NaN
9,188,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,4,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
10,189,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
11,190,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,3,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
12,191,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
13,192,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,7,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
14,193,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
15,194,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
16,195,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
17,196,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
18,197,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,...,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021,NaN

## Iteration 6

In [55]:
from tabula import read_pdf
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    for file in pdf_filenames:
        print(file, end='...')
        try:
            file = f'{filepath}/'.replace('\\','/')+file if filepath else file
            df_list = read_pdf(file, pages=pages)
            # df_temp = pd.concat(df_list)
            # df_temp.columns = df_temp.columns.str.replace(r'Unnamed: [\d*]', 'index', regex=True)
            # df_temp.columns = df_temp.columns.str.replace('\r', '')
            # df_temp.columns = df_temp.columns.str.replace('cosed', 'closed')
            # df_temp = df_temp.set_index('index')
            # df_temp.index.name = None
            # dfs_list.append(df_temp)
            dfs_list.append(df_list)
        except:
            return dfs_list
        print('Done')
    # unique_cols_dict = {}
    # for i, df in enumerate(dfs_list):
    #     other_dfs = dfs_list[:i] + dfs_list[i+1:]
    #     other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
    #     unique_columns = set(df.columns) - other_cols
    #     unique_cols_dict[f'part{i+1}'] = unique_columns
    #     print(f'Columns unique to part{i+1}: {unique_columns if len(unique_columns)>0 else "none"}')
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
        except:
            print('Unable to save outputs')

    return dfs_list

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(2,n_docs+1)]
dfs6 = parse_pdf(filenames, pages='1-10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs6[0][2]

Extracting the following files:
F22-1445 Records_Part2.pdf...Done

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
3,NaN,HA,workplace name,NaN,workplace,address,city,health,er_active,es,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
4,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,217.0,FHA,NaN,NaN,NaN,NaN,SURREY,4/19/2021,5/3/2021,NaN,...,Yes,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,218.0,FHA,NaN,NaN,NaN,NaN,DELTA,4/19/2021,5/1/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,219.0,FHA,NaN,NaN,NaN,NaN,SURREY,4/19/2021,4/29/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
10,220.0,FHA,NaN,NaN,NaN,NaN,MAPLE RIDGE,4/19/2021,5/5/2021,NaN,...,Yes,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,16-2021
11,221.0,FHA,NaN,NaN,NaN,NaN,COQUITLAM,4/19/2021,5/26/2021,NaN,...,Yes,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021
12,222.0,FHA,NaN,NaN,NaN,NaN,DELTA,4/19/2021,5/17/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,PORT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,223.0,FHA,NaN,NaN,NaN,NaN,COQUITLAM,4/19/2021,4/30/2021,NaN,...,Yes,Yes,Unknown,4/22/2021,No,No,NaN,No,16-2021,16-2021
15,224.0,FHA,NaN,NaN,NaN,NaN,DELTA,4/19/2021,5/7/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
16,225.0,FHA,NaN,NaN,NaN,NaN,ABBOTSFORD,4/19/2021,5/16/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
17,226.0,FHA,NaN,NaN,NaN,NaN,SURREY,4/19/2021,4/20/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,227.0,VCH,NaN,NaN,NaN,NaN,Richmond,4/19/2021,NaN,4/19/2021,...,No,No,No,NaN,No,Yes,NaN,No,16-2021,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,228.0,FHA,NaN,NaN,NaN,NaN,BURNABY,4/20/2021,5/1/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
25,229.0,FHA,NaN,NaN,NaN,NaN,SURREY,4/20/2021,4/28/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,230.0,FHA,NaN,NaN,NaN,NaN,BURNABY,4/20/2021,4/30/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,231.0,FHA,NaN,NaN,NaN,NaN,COQUITLAM,4/20/2021,5/6/2021,NaN,...,Yes,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,16-2021
31,232.0,FHA,NaN,NaN,NaN,NaN,DELTA,4/20/2021,5/4/2021,NaN,...,Yes,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,16-2021
32,233.0,FHA,NaN,NaN,NaN,NaN,SURREY,4/20/2021,5/3/2021,NaN,...,Yes,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,16-2021
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,234.0,FHA,NaN,NaN,NaN,NaN,ANGLEY,4/20/2021,5/9/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
36,235.0,FHA,NaN,NaN,NaN,NaN,SURREY,4/20/2021,4/27/2021,NaN,...,Yes,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,236.0,FHA,NaN,NaN,NaN,NaN,BURNABY,4/20/2021,5/4/2021,NaN,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,237.0,FHA,NaN,NaN,NaN,NaN,DELTA,4/20/2021,4/30/2021,NaN,...,Yes,No,Unknown,4/21/2021,Yes,No,NaN,No,16-2021,16-2021
42,238.0,FHA,NaN,NaN,NaN,NaN,ABBOTSFORD,4/20/2021,5/5/2021,NaN,...,Yes,Yes,Unknown,4/22/2021,No,No,NaN,No,16-2021,16-2021

In [57]:
dfs6[0][1]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_clust\rer_confirm\red_public_\rhealth,date_clust\rer_no_long\rer_active,earliest_re\rported_cas\res,latest_repor\rted_cases,workplace_clas\rsification,...,closure_\ry_n,closed_by\r_order,voluntary_\rclosure,closure_da\rte,partially_\rclosed,open,days_s\rince_la\rst_cas\re,active_clu\rsters,cluster_c\ronfirmed\r_epidate,cluster_cl\rosed_epid\rate
0,198,FHA,NaN,s.22(1),PORT\rCOQUITLAM,4/17/2021,4/26/2021,NaN,NaN,Transportation,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
1,199,FHA,NaN,BURNABY,4/17/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
2,200,VCH,NaN,North\rVancouver,4/17/2021,NaN,4/17/2021,5/2/2021,Retail,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
3,201,VCH,NaN,West\rVancouver,4/17/2021,NaN,4/17/2021,5/14/2021,Maintenance/T\rrades/Construc\rtion,NaN,...,Yes,No,4/24/2021,No,No,NaN,No,15-2021,16-2021,NaN
4,202,NHA,NaN,Unknown,4/17/2021,5/20/2021,NaN,NaN,Health Care\rFacility\r(Acute/LTC),NaN,...,No,No,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
5,203,FHA,NaN,ABBOTSFORD,4/18/2021,4/18/2021,NaN,NaN,Other,5,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
6,204,FHA,NaN,PORT\rCOQUITLAM,4/18/2021,5/6/2021,NaN,NaN,Gym/Fitness,5,...,Yes,Unknown,4/19/2021,No,No,NaN,No,16-2021,16-2021,NaN
7,205,FHA,NaN,SURREY,4/18/2021,5/5/2021,NaN,NaN,Retail,13,...,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021,NaN
8,206,FHA,NaN,SURREY,4/18/2021,5/5/2021,NaN,NaN,Gym/Fitness,3,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
9,207,VCH,NaN,North\rVancouver,4/18/2021,NaN,4/18/2021,5/12/2021,School/Daycar\re,NaN,...,Yes,No,4/6/2021,No,No,NaN,No,16-2021,14-2021,NaN
10,208,NHA,NaN,Unknown,4/18/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,16-2021,NaN,NaN
11,209,FHA,NaN,SURREY,4/19/2021,4/29/2021,NaN,NaN,Office,6,...,No,Unknown,4/21/2021,Yes,No,NaN,No,16-2021,16-2021,NaN
12,210,FHA,NaN,BURNABY,4/19/2021,5/7/2021,NaN,NaN,Office,10,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
13,211,FHA,NaN,SURREY,4/19/2021,5/4/2021,NaN,NaN,Manufacturing\r/Industry,3,...,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021,NaN
14,212,FHA,NaN,LANGLEY,4/19/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,4,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
15,213,FHA,NaN,LANGLEY,4/19/2021,5/3/2021,NaN,NaN,Manufacturing\r/Industry,3,...,Yes,Unknown,4/21/2021,No,No,NaN,No,16-2021,16-2021,NaN
16,214,FHA,NaN,BURNABY,4/19/2021,5/1/2021,NaN,NaN,Office,3,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
17,215,FHA,NaN,LANGLEY,4/19/2021,5/10/2021,NaN,NaN,Food\rProcessing,7,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
18,216,FHA,NaN,DELTA,4/19/2021,4/26/2021,NaN,NaN,Farm/Agricultu\rre,5,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN

In [60]:
dfs6[0][2].head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
3,NaN,HA,workplace name,NaN,workplace,address,city,health,er_active,es,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
4,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
dfs6[0][3].head()

,Unnamed: 0,HA,workplacename,workplaceaddress,city,date_clust\rer_confirm\red_public_\rhealth,date_clust\rer_no_long\rer_active,earliest_re\rported_cas\res,latest_repor\rted_cases,workplace_clas\rsification,...,closure_\ry_n,closed_by\r_order,voluntary_\rclosure,closure_da\rte,partially_\rclosed,open,days_s\rince_la\rst_cas\re,active_clu\rsters,cluster_c\ronfirmed\r_epidate,cluster_cl\rosed_epid\rate
0,239,FHA,s.22(1),ABBOTSFORD,4/20/2021,4/29/2021,NaN,NaN,Office,4,...,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN
1,240,FHA,LANGLEY,4/20/2021,4/20/2021,NaN,NaN,Personal Care,3,3,...,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN,NaN
2,241,FHA,PORT\rCOQUITLAM,4/20/2021,4/20/2021,NaN,NaN,Gym/Fitness,5,5,...,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN,NaN
3,242,FHA,ABBOTSFORD,4/20/2021,5/2/2021,NaN,NaN,Office,3,3,...,Unknown,4/21/2021,Yes,No,NaN,No,16-2021,16-2021,NaN,NaN
4,243,VIHA,Duncan,4/20/2021,NaN,4/15/2021,4/20/2021,Office,0,3,...,No,NaN,Unknown,Yes,70,No,16-2021,NaN,NaN,NaN

In [61]:
dfs6[0][4].head()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_clust\rer_confirm\red_public_\rhealth,date_clust\rer_no_long\rer_active,earliest_re\rported_cas\res,latest_repor\rted_cases,workplace_clas\rsification,...,closure_\ry_n,closed_by\r_order,voluntary_\rclosure,closure_da\rte,partially_\rclosed,open,days_s\rince_la\rst_cas\re,active_clu\rsters,cluster_c\ronfirmed\r_epidate,cluster_cl\rosed_epid\rate
0,261,FHA,s.22(1),SURREY,4/22/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,4,...,Yes,Unknown,4/24/2021,No,No,NaN,No,16-2021,16-2021,NaN
1,262,FHA,ABBOTSFORD,4/22/2021,5/12/2021,NaN,NaN,Manufacturing\r/Industry,3,3,...,Unknown,NaN,No,No,NaN,No,16-2021,NaN,NaN,NaN
2,263,FHA,LANGLEY,4/22/2021,5/10/2021,NaN,NaN,Retail,6,6,...,Unknown,4/23/2021,No,No,NaN,No,16-2021,16-2021,NaN,NaN
3,264,FHA,SURREY,4/22/2021,5/4/2021,NaN,NaN,Restaurant/Bar\r/Lounge,5,5,...,Unknown,4/22/2021,No,No,NaN,No,16-2021,16-2021,NaN,NaN
4,265,FHA,SURREY,4/23/2021,5/3/2021,NaN,NaN,Gym/Fitness,5,5,...,Unknown,4/23/2021,No,No,NaN,No,16-2021,16-2021,NaN,NaN

## Iteration 7

In [80]:
from tabula import read_pdf
import json
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            file = filepath+file
            df_list = read_pdf(file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list().sort()
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if df_list[page_number].columns.to_list().sort() == page1_columns:
                    file_dfs.append(df_list[page_number])
                else:
                    file_dfs.append(pd.DataFrame(columns=page1_columns, index=df_list[page_number].iloc[:,0].values))
                    unparsed_pages[file] = page_number
                    print(f'Unable to parse {file} page {page_number}')

            final_file_df = pd.concat(file_dfs)
            # df_temp.columns = df_temp.columns.str.replace(r'Unnamed: [\d*]', 'index', regex=True)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            # df_temp = df_temp.set_index('index')
            # df_temp.index.name = None
            dfs_list.append(final_file_df)
        except:
            print(f'Unable to parse {file}')
            return dfs_list
        print('\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[f'part{i+1}'] = unique_columns
        print(f'Columns unique to part{i+1}: {unique_columns if len(unique_columns)>0 else "none"}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs7, reference7 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs7[0]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0...
page 1...
	Done
F22-1445 Records_Part2.pdf...page 0...
page 1...
	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters', 'cases_', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 2', 'Unnamed: 10', 'Unnamed: 19', 'Unnamed: 11', 'Unnamed: 21', 'Unnamed: 17', 'Unnamed: 20', 'Unnamed: 18', 'Unnamed: 14', 'Unnamed: 6', 'Unnamed: 16', 'Unnamed: 7', 'Unnamed: 12', 'Unnamed: 9', 'Unnamed: 13', 'Unnamed: 15', 'Unnamed: 3', 'Unnamed: 1', 'Unnamed: 8'}

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
6,7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
11,12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
12,13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
13,14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
14,15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
15,16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
0,150,FHA,NaN,.22(1),BBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agriculture,...,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021
1,151,FHA,NaN,URNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,7,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
2,152,FHA,NaN,ELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,6,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
3,153,FHA,NaN,ELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
4,154,FHA,NaN,ORT\rOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
5,155,FHA,NaN,ORT\rOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
6,156,FHA,NaN,URREY,4/14/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
7,157,FHA,NaN,URREY,4/14/2021,4/27/2021,NaN,NaN,Retail,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
8,158,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021,NaN
9,159,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Retail,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
10,160,NHA,NaN,nknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,3,...,Yes,No,Yes,NaN,Unknown,No,NaN,15-2021,NaN,NaN
11,161,FHA,NaN,URNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing/I\rndustry,25,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
12,162,FHA,NaN,URNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
13,163,FHA,NaN,ANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
14,164,FHA,NaN,ANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/17/2021,No,No,NaN,15-2021,15-2021,NaN
15,165,FHA,NaN,URREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
16,166,FHA,NaN,URNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN

In [82]:
reference7['unparsed pages']

{}

In [83]:
dfs7[1]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [85]:
[i for i in dfs7[1]['Unnamed: 0']]

[179.0,
 180.0,
 181.0,
 182.0,
 183.0,
 184.0,
 185.0,
 186.0,
 187.0,
 188.0,
 189.0,
 190.0,
 191.0,
 192.0,
 193.0,
 194.0,
 195.0,
 196.0,
 197.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 347.0,
 nan,
 nan,
 nan,
 348.0,
 nan,
 nan,
 349.0,
 nan,
 nan,
 nan,
 350.0,
 nan,
 nan,
 nan,
 351.0,
 352.0,
 nan,
 nan,
 nan,
 nan,
 353.0,
 nan,
 354.0,
 nan,
 nan,
 355.0,
 nan,
 nan,
 nan,
 356.0,
 nan,
 nan,
 nan,
 357.0,
 nan,
 nan,
 nan,
 nan,
 358.0,
 nan,
 nan,
 359.0]

In [91]:
dfs7[1][dfs7[1]['Unnamed: 0'].isna()].filter(regex='Unnamed')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
2,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,latest_repor,workplace_clas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
3,NaN,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
4,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df1 = pd.DataFrame(columns=['a', 'b'], index=[i for i in range(3)])
df1

     a    b
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

In [73]:
df1.columns.to_list().sort() == df1.columns.to_list().sort()

True

## Iteration 8

In [225]:
from tabula import read_pdf
import json
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            file = filepath+file
            df_list = read_pdf(file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list().sort()
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if df_list[page_number].columns.to_list().sort() == page1_columns:
                    file_dfs.append(df_list[page_number])
                else:
                    file_dfs.append(pd.DataFrame(columns=page1_columns, index=df_list[page_number].iloc[:,0].values))
                    unparsed_pages[file] = page_number
                    print(f'Unable to parse {file} page {page_number}')

            final_file_df = file_dfs
            # final_file_df = pd.concat(file_dfs)
            # df_temp.columns = df_temp.columns.str.replace(r'Unnamed: [\d*]', 'index', regex=True)
            # final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            # df_temp = df_temp.set_index('index')
            # df_temp.index.name = None
            dfs_list.append(final_file_df)
        except:
            print(f'Problem parsing {file}')
            return dfs_list
        print('\tDone')
    # unique_cols_dict = {}
    # for i, df in enumerate(dfs_list):
    #     other_dfs = dfs_list[:i] + dfs_list[i+1:]
    #     other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
    #     unique_columns = set(df.columns) - other_cols
    #     unique_cols_dict[f'part{i+1}'] = unique_columns
    #     print(f'Columns unique to part{i+1}: {unique_columns if len(unique_columns)>0 else "none"}')
    # reference_dict['unique columns'] = unique_cols_dict
    reference_dict['unparsed pages'] = unparsed_pages
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs8, reference8 = parse_pdf(filenames, pages='1,10', filename=None)

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......	Done
F22-1445 Records_Part2.pdf...page 0......page 1......	Done

In [226]:
dfs8[0][0]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
6,7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
11,12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
12,13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
13,14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
14,15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
15,16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN

In [97]:
dfs8[0][1].head()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,150,FHA,NaN,.22(1),BBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agriculture,...,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021
1,151,FHA,NaN,URNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,7,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
2,152,FHA,NaN,ELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,6,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
3,153,FHA,NaN,ELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
4,154,FHA,NaN,ORT\rOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN

In [228]:
dfs8[1][0]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
5,184,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
6,185,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
7,186,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,25,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
8,187,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,5,...,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021,NaN
9,188,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,4,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
10,189,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
11,190,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,3,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
12,191,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
13,192,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,7,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
14,193,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
15,194,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
16,195,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
17,196,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
18,197,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,...,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021,NaN

In [115]:
dfs8[1][1]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
2,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,latest_repor,workplace_clas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
3,NaN,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
4,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
25,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
32,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [108]:
sorted(dfs8[0][0].columns.to_list()) == sorted(dfs8[0][1].columns.to_list())

True

In [118]:
dfs8[1][1].loc[51, 'Unnamed: 0'].astype(int)

359

In [121]:
dfs8[1][1][dfs8[1][1]['Unnamed: 0'] > 0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
9,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
13,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
16,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
20,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
24,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
25,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
30,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
32,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
35,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
39,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
43,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
48,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
51,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [137]:
dfs8[1][1][dfs8[1][1]['Unnamed: 0'] > 0]['Unnamed: 0'].astype(int)

9     347
13    348
16    349
20    350
24    351
25    352
30    353
32    354
35    355
39    356
43    357
48    358
51    359
Name: Unnamed: 0, dtype: int32

In [148]:
dfs8[1][1]['Unnamed: 0'].fillna(0).astype(int)

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9     347
10      0
11      0
12      0
13    348
14      0
15      0
16    349
17      0
18      0
19      0
20    350
21      0
22      0
23      0
24    351
25    352
26      0
27      0
28      0
29      0
30    353
31      0
32    354
33      0
34      0
35    355
36      0
37      0
38      0
39    356
40      0
41      0
42      0
43    357
44      0
45      0
46      0
47      0
48    358
49      0
50      0
51    359
Name: Unnamed: 0, dtype: int32

## Iteration 9

In [149]:
from tabula import read_pdf
import json
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            file = filepath+file
            df_list = read_pdf(file, pages=pages)
            file_dfs = []
            page1_columns = sorted(df_list[0].columns.str.replace('\r', '').to_list())
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns:
                    df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'] = df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'].astype(int)
                    file_dfs.append(df_list[page_number])
                else:
                    placeholder = pd.DataFrame(columns=page1_columns)
                    placeholder['Unnamed: 0'] = df_list[page_number].iloc[:,0].fillna(0).values.astype(int)
                    file_dfs.append(placeholder)
                    unparsed_pages[file] = page_number
                    print(f'\n\tUnable to parse page {page_number} of {file}', sep='')

            final_file_df = pd.concat(file_dfs)
            # df_temp.columns = df_temp.columns.str.replace(r'Unnamed: [\d*]', 'index', regex=True)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            # df_temp = df_temp.set_index('index')
            # df_temp.index.name = None
            dfs_list.append(final_file_df)
        except:
            print(f'Unable to parse {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[f'part{i+1}'] = unique_columns
        print(f'Columns unique to part{i+1}: {unique_columns if len(unique_columns)>0 else "none"}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs9, reference9 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs9[0]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	Unable to parse page 1 of C:/Users/silvh/OneDrive/lighthouse/portfolio-projects/BC-Covid-workplace-closures/data/raw//F22-1445 Records_Part2.pdf

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
6,7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
11,12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
12,13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
13,14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
14,15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
15,16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
0,150,FHA,NaN,.22(1),BBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agriculture,...,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021
1,151,FHA,NaN,URNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,7,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
2,152,FHA,NaN,ELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,6,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
3,153,FHA,NaN,ELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
4,154,FHA,NaN,ORT\rOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
5,155,FHA,NaN,ORT\rOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
6,156,FHA,NaN,URREY,4/14/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
7,157,FHA,NaN,URREY,4/14/2021,4/27/2021,NaN,NaN,Retail,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
8,158,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021,NaN
9,159,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Retail,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
10,160,NHA,NaN,nknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,3,...,Yes,No,Yes,NaN,Unknown,No,NaN,15-2021,NaN,NaN
11,161,FHA,NaN,URNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing/I\rndustry,25,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
12,162,FHA,NaN,URNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
13,163,FHA,NaN,ANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
14,164,FHA,NaN,ANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/17/2021,No,No,NaN,15-2021,15-2021,NaN
15,165,FHA,NaN,URREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
16,166,FHA,NaN,URNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN

In [150]:
dfs9[1].tail(10)

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
42,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [159]:
dfs9[1].head().reindex()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN

In [114]:
dfs9[1].loc[359.0]

Unnamed: 0                              NaN
HA                                      NaN
workplace_name                          NaN
workplace_address                       NaN
city                                    NaN
date_cluster_confirmed_public_health    NaN
date_cluster_no_longer_active           NaN
earliest_reported_cases                 NaN
latest_reported_cases                   NaN
workplace_classification                NaN
cases_when_cluster_confirmed            NaN
total_cases                             NaN
workplace_status                        NaN
closure_y_n                             NaN
closed_by_order                         NaN
voluntary_closure                       NaN
closure_date                            NaN
partially_closed                        NaN
open                                    NaN
days_since_last_case                    NaN
active_clusters                         NaN
cluster_confirmed_epidate               NaN
cluster_closed_epidate                  NaN
Name: 359.0, dtype: object

In [151]:
reference9['unparsed pages']

{'C:/Users/silvh/OneDrive/lighthouse/portfolio-projects/BC-Covid-workplace-closures/data/raw//F22-1445 Records_Part2.pdf': 1}

## Iteration 10: Parses w/o adding extra columns

In [185]:
from tabula import read_pdf
import json
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = sorted(df_list[0].columns.str.replace('\r', '').to_list())
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns:
                    df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'] = df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'].astype(int)
                    file_dfs.append(df_list[page_number])
                else:
                    placeholder = pd.DataFrame(columns=page1_columns)
                    placeholder['Unnamed: 0'] = df_list[page_number].iloc[:,0].fillna(0).values.astype(int)
                    file_dfs.append(placeholder)
                    unparsed_pages[file] = page_number
                    print(f'\n\t**Unable to parse page {page_number} of {file}**', sep='')

            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs10, reference9 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs10[0]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	**Unable to parse page 1 of F22-1445 Records_Part2.pdf**

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
5,6,FHA,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
6,7,FHA,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
7,8,FHA,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,4,4,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
8,9,FHA,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,50,50,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
9,10,FHA,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,26,26,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
10,11,FHA,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,16,16,...,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
11,12,FHA,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
12,13,FHA,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,7,7,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
13,14,FHA,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,3,3,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
14,15,FHA,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,9,9,...,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021,NaN,NaN
15,16,FHA,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021,NaN,NaN
16,150,FHA,NaN,.22(1),BBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agriculture,...,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021
17,151,FHA,NaN,URNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,7,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
18,152,FHA,NaN,ELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,6,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
19,153,FHA,NaN,ELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
20,154,FHA,NaN,ORT\rOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
21,155,FHA,NaN,ORT\rOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
22,156,FHA,NaN,URREY,4/14/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN
23,157,FHA,NaN,URREY,4/14/2021,4/27/2021,NaN,NaN,Retail,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
24,158,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021,NaN
25,159,FHA,NaN,URREY,4/14/2021,4/24/2021,NaN,NaN,Retail,5,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021,NaN
26,160,NHA,NaN,nknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,3,...,Yes,No,Yes,NaN,Unknown,No,NaN,15-2021,NaN,NaN
27,161,FHA,NaN,URNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing/I\rndustry,25,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021,NaN
28,162,FHA,NaN,URNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
29,163,FHA,NaN,ANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
30,164,FHA,NaN,ANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing/I\rndustry,5,...,Yes,Yes,Unknown,4/17/2021,No,No,NaN,15-2021,15-2021,NaN
31,165,FHA,NaN,URREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021,NaN
32,166,FHA,NaN,URNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN,NaN

In [186]:
reference9

{'unparsed pages': {'F22-1445 Records_Part2.pdf': 1},
 'unique columns': {'F22-1445 Records_Part2.pdf': {'active_clusters'}}}

In [191]:
dfs10[1][dfs10[1]['index']==0]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
19,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Iteration 11

In [198]:
from tabula import read_pdf
import json
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = sorted(df_list[0].columns.str.replace('\r', '').to_list())
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns:
                    # df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'] = df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'].astype(int)
                    file_dfs.append(df_list[page_number])
                else:
                    df_list[page_number].columns = page1_columns
                    # placeholder = pd.DataFrame(columns=page1_columns)
                    # placeholder['Unnamed: 0'] = df_list[page_number].iloc[:,0].fillna(0).values.astype(int)
                    # file_dfs.append(placeholder)
                    unparsed_pages[file] = page_number
                    file_dfs.append(df_list[page_number])
                    print(f'\n\t**Unable to parse columns for page {page_number} of {file}**', sep='')

            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs11, reference11 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs11[1]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	**Unable to parse columns for page 1 of F22-1445 Records_Part2.pdf**

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,remaining,NaN,NaN,NaN
67,FHA,358.0,18-2021,NaN,SURREY,4,4,No,No,No,...,NaN,5/4/2021,Yes,5/14/2021,NaN,Unknown,open,NaN,Retail,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,NaN
70,FHA,359.0,18-2021,NaN,DELTA,3,3,Yes,Yes,No,...,NaN,5/4/2021,No,5/20/2021,5/5/2021,Unknown,Closed,NaN,tion,NaN

In [211]:
dfs11[1][(dfs11[1]['HA'].apply(lambda x: isinstance(x, float)) == True) & (dfs11[1]['HA'].isna()==False)]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
28,FHA,347.0,18-2021,NaN,ANGLEY,3,3,No,No,No,...,NaN,5/3/2021,Yes,5/11/2021,NaN,Unknown,transmission,NaN,/Industry,NaN
32,FHA,348.0,18-2021,NaN,DELTA,4,4,No,No,No,...,NaN,5/3/2021,Yes,5/12/2021,NaN,Unknown,measures,NaN,Warehouse,NaN
35,FHA,349.0,18-2021,NaN,COQUITLAM,8,8,Yes,Yes,No,...,NaN,5/3/2021,No,5/19/2021,5/4/2021,Unknown,Closed,NaN,tion,NaN
39,FHA,350.0,18-2021,NaN,MISSION,6,6,No,No,No,...,NaN,5/3/2021,Yes,5/20/2021,NaN,Unknown,measures,NaN,re,NaN
43,FHA,351.0,18-2021,NaN,SURREY,8,8,No,No,No,...,NaN,5/3/2021,Yes,5/20/2021,NaN,Unknown,measures,NaN,/Industry,NaN
44,VIHA,352.0,18-2021,55,Victoria,0,5,Yes,No,No,...,5/1/2021,5/3/2021,No,NaN,NaN,Yes,Closed,NaN,Other,5/5/2021
49,VCH,353.0,18-2021,NaN,Vancouver,NaN,4,Yes,No,No,...,5/3/2021,5/3/2021,No,NaN,NaN,No,PH,NaN,tion,5/21/2021
51,NHA,354.0,18-2021,NaN,Unknown,1,10,Yes,Yes,No,...,NaN,5/3/2021,No,6/15/2021,#########,No,order,NaN,re,NaN
54,FHA,355.0,18-2021,NaN,SURREY,3,3,Yes,Yes,No,...,NaN,5/4/2021,No,5/12/2021,5/5/2021,Unknown,Closed,NaN,tion,NaN
58,FHA,356.0,18-2021,NaN,ABBOTSFORD,3,3,No,No,No,...,NaN,5/4/2021,Yes,5/27/2021,NaN,Unknown,measures,NaN,tion,NaN
62,FHA,357.0,18-2021,NaN,SURREY,8,8,No,No,No,...,NaN,5/4/2021,Yes,5/20/2021,NaN,Unknown,measures,NaN,tion,NaN
67,FHA,358.0,18-2021,NaN,SURREY,4,4,No,No,No,...,NaN,5/4/2021,Yes,5/14/2021,NaN,Unknown,open,NaN,Retail,NaN
70,FHA,359.0,18-2021,NaN,DELTA,3,3,Yes,Yes,No,...,NaN,5/4/2021,No,5/20/2021,5/5/2021,Unknown,Closed,NaN,tion,NaN

## Iteration 12

In [298]:
from tabula import read_pdf
import json
import re
def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    # df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'] = df_list[page_number][df_list[page_number]['Unnamed: 0'] > 0]['Unnamed: 0'].astype(int)
                    file_dfs.append(df_list[page_number])
                else:
                    df_list[page_number].columns = page1_columns
                    # placeholder = pd.DataFrame(columns=page1_columns)
                    # placeholder['Unnamed: 0'] = df_list[page_number].iloc[:,0].fillna(0).values.astype(int)
                    # file_dfs.append(placeholder)
                    unparsed_pages[file] = page_number
                    file_dfs.append(df_list[page_number])
                    print(f'\n\t**Unable to parse columns for page {page_number} of {file}**', sep='')

            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs12, reference12 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs12[1]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	**Unable to parse columns for page 1 of F22-1445 Records_Part2.pdf**

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [299]:
dfs12[1].loc[15:]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
15,194.0,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
16,195.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
17,196.0,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
18,197.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,...,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021,NaN
19,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
21,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,latest_repor,workplace_clas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
22,NaN,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
23,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
44,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
51,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [223]:
reference12

{'unparsed pages': {'F22-1445 Records_Part2.pdf': 1},
 'unique columns': {'F22-1445 Records_Part2.pdf': {'active_clusters'}}}

In [222]:
dfs12[0].head()

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,3,3,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,8,8,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,4,4,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,12,12,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,5,5,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN

In [215]:
dfs12[1][~(dfs12[1]['HA'].isna())]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
5,184.0,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
6,185.0,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
7,186.0,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,25,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
8,187.0,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,5,...,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021,NaN
9,188.0,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,4,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
10,189.0,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
11,190.0,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,3,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
12,191.0,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
13,192.0,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,7,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
14,193.0,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
15,194.0,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
16,195.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
17,196.0,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
18,197.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,...,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021,NaN
22,NaN,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
28,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
32,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
35,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
39,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
43,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
44,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
49,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
51,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
54,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
58,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
62,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
67,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
70,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

In [216]:
dfs12[1][(dfs12[1]['index'].isna())]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
19,NaN,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
21,NaN,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,latest_repor,workplace_clas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
22,NaN,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
23,NaN,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [234]:
del dfs12_p2p10, reference12_p2p10

# `merge_rows` function

In [247]:
def merge_rows(df, id_column='index', fill_method='bfill'):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    df[id_column].fillna(method=fill_method, inplace=True)
    
    # Group the rows by the unique ID column and aggregate the values in each group
    grouped_df = df.groupby(id_column, as_index=False).agg(lambda x: ''.join(str(v) for v in x if type(v)==str))
    
    # Return the merged dataframe
    return grouped_df


merged_df = merge_rows(dfs12[1].loc[25:])

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2253185893.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[id_column].fillna(method=fill_method, inplace=True)

In [250]:
merged_df.head().loc[0, 'workplace_name']

''

In [252]:
merged_df.head()

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,347.0,FHA,,,ANGLEY,5/3/2021,5/11/2021,,,Manufacturing/Industry,...,No,No,Unknown,,No,Yes,,No,18-2021,
1,348.0,FHA,,,DELTA,5/3/2021,5/12/2021,,,Warehouse,...,No,No,Unknown,,No,Yes,,No,18-2021,
2,349.0,FHA,,,COQUITLAM,5/3/2021,5/19/2021,,,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/4/2021,No,No,,No,18-2021,18-2021
3,350.0,FHA,,,MISSION,5/3/2021,5/20/2021,,,Farm/Agriculture,...,No,No,Unknown,,No,Yes,,No,18-2021,
4,351.0,FHA,,,SURREY,5/3/2021,5/20/2021,,,Manufacturing/Industry,...,No,No,Unknown,,No,Yes,,No,18-2021,

In [257]:
merged_df.head().replace('', None)

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,347.0,FHA,None,None,ANGLEY,5/3/2021,5/11/2021,None,None,Manufacturing/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
1,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
2,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
3,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,Farm/Agriculture,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
4,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,Manufacturing/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None

In [251]:
dfs12[1].loc[25:]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
25,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
29,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
33,349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
36,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
40,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
44,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
45,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
50,354.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
51,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
52,355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
55,356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
59,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
63,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
68,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021

## Iteration 2

In [268]:
def merge_rows(df, id_column='index', fill_method='bfill'):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group
    grouped_df = df.groupby(id_column, as_index=False).agg(lambda x: ''.join(str(v) for v in x if type(v)==str))
    
    # Return the merged dataframe
    return grouped_df.replace('', None)


merged_df = merge_rows(dfs12[1].loc[25:])
merged_df

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\3718907275.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[id_column] = df[id_column].fillna(method=fill_method)

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,347.0,FHA,None,None,ANGLEY,5/3/2021,5/11/2021,None,None,Manufacturing/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
1,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
2,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
3,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,Farm/Agriculture,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
4,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,Manufacturing/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
5,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,None,Unknown,No,55,No,18-2021,None
6,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,Maintenance/Trades/Construction,...,Yes,No,No,None,Yes,No,None,No,18-2021,None
7,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,Farm/Agriculture,...,Yes,Yes,No,#########,Unknown,No,None,No,18-2021,13-4438965
8,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
9,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
10,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
11,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
12,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

In [275]:
dfs12[1].loc[25:]['index'].isna().sum()

0

# `parse_pdf` + `merge_rows`

In [287]:
from tabula import read_pdf
import json
import re

def merge_rows(df, id_column='Unnamed: 0', fill_method='bfill'):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group
    grouped_df = df.groupby(id_column, as_index=False).agg(lambda x: ''.join(str(v) for v in x if type(v)==str))
    
    # Return the merged dataframe
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns
                    unparsed_pages[file] = page_number+1
                    file_dfs.append(df_list[page_number])
                    print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
                file_dfs.append(
                    merge_rows(df_list[page_number]) if df_list[page_number]['Unnamed: 0'].isna().sum() > 0 else df_list[page_number]
                    # df_list[page_number]
                    # merge_rows(df_list[page_number])
                    )
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs, reference = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs[1]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
80,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
81,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
82,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
83,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

In [290]:
dfs[1].dtypes

index                                   float64
HA                                       object
workplace_name                           object
workplace_address                        object
city                                     object
date_cluster_confirmed_public_health     object
date_cluster_no_longer_active            object
earliest_reported_cases                  object
latest_reported_cases                    object
workplace_classification                 object
cases_when_cluster_confirmed             object
total_cases                              object
workplace_status                         object
closure_y_n                              object
closed_by_order                          object
voluntary_closure                        object
closure_date                             object
partially_closed                         object
open                                     object
days_since_last_case                     object
active_clusters                          object
cluster_confirmed_epidate                object
cluster_closed_epidate                   object
dtype: object

In [288]:
reference

{'unparsed pages': {'F22-1445 Records_Part2.pdf': 2},
 'unique columns': {'F22-1445 Records_Part2.pdf': {'active_clusters'}}}

In [293]:
dfs[1].tail(14)

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
70,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
71,347.0,HAFHA,workplace_names.22(1),workplace_address,cityANGLEY,date_cluster_confirmed_public_health5/3/2021,date_cluster_no_longer_active5/11/2021,earliest_reported_cases,latest_reported_cases,workplace_classificationManufacturing/Industry,...,closure_y_nNo,closed_by_orderNo,voluntary_closureUnknown,closure_date,partially_closedNo,openYes,days_since_last_case,active_clustersNo,cluster_confirmed_epidate18-2021,cluster_closed_epidate
72,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
73,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
74,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,Farm/Agriculture,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
75,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,Manufacturing/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
76,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,None,Unknown,No,55,No,18-2021,None
77,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,Maintenance/Trades/Construction,...,Yes,No,No,None,Yes,No,None,No,18-2021,None
78,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,Farm/Agriculture,...,Yes,Yes,No,#########,Unknown,No,None,No,18-2021,13-4438965
79,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
80,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
81,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
82,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
83,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

## iteration 2

In [361]:
from tabula import read_pdf
import json
import re

def merge_rows(df, id_column=['Unnamed: 0'], fill_method='bfill'):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print('Original df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group
    grouped_df = df.groupby(id_column, as_index=False).agg(lambda x: ''.join(str(v) for v in x if type(v)==str))
    columns_to_fill = df.drop(columns=id_column).columns
    # print('columns to fill:', columns_to_fill)
    # grouped_df = df.groupby(id_column, as_index=True).agg(
    #     lambda x: ''.join(str(v) for v in x if (type(v)==str)))
    
    # df.groupby(id_column, as_index=False)[columns_to_fill].agg(
    #     lambda x: print(x.name) if x.name in columns_to_fill else print('x'))
    
    # Return the merged dataframe
    print('Transformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns
                    unparsed_pages[file] = page_number+1
                    file_dfs.append(df_list[page_number])
                    print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
                file_dfs.append(
                    merge_rows(df_list[page_number]) if df_list[page_number]['Unnamed: 0'].isna().sum() > 0 else df_list[page_number]
                    # df_list[page_number]
                    # merge_rows(df_list[page_number])
                    )
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs, reference = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs[1]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**
Original df shape:  (52, 23)
Transformed df shape: (13, 23)

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
80,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
81,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
82,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
83,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

In [366]:
dfs[1].loc[19:69]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
19,347.0,NaN,NaN,NaN,NaN,date_clust,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,days_s,NaN,NaN,NaN
20,347.0,NaN,NaN,NaN,NaN,er_confirm,date_clust,earliest_re,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ince_la,NaN,cluster_c,cluster_cl
21,347.0,NaN,NaN,NaN,NaN,ed_public_,er_no_long,ported_cas,latest_repor,workplace_clas,...,closure_,closed_by,voluntary_,closure_da,partially_,NaN,st_cas,active_clu,onfirmed,osed_epid
22,347.0,HA,workplace_name,workplace_address,city,health,er_active,es,ted_cases,sification,...,y_n,_order,closure,te,closed,open,e,sters,_epidate,ate
23,347.0,NaN,s.22(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,347.0,FHA,NaN,NaN,ANGLEY,5/3/2021,5/11/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
29,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,348.0,FHA,NaN,NaN,DELTA,5/3/2021,5/12/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
33,349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,349.0,FHA,NaN,NaN,COQUITLAM,5/3/2021,5/19/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,NaN,No,18-2021,18-2021
36,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,350.0,FHA,NaN,NaN,MISSION,5/3/2021,5/20/2021,NaN,NaN,re,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
40,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,351.0,FHA,NaN,NaN,SURREY,5/3/2021,5/20/2021,NaN,NaN,/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
44,352.0,VIHA,NaN,NaN,Victoria,5/3/2021,NaN,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,55,No,18-2021,NaN
45,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,353.0,VCH,NaN,NaN,Vancouver,5/3/2021,NaN,5/3/2021,5/21/2021,tion,...,Yes,No,No,NaN,Yes,No,NaN,No,18-2021,NaN
50,354.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Farm/Agricultu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-
51,354.0,NHA,NaN,NaN,Unknown,5/3/2021,6/15/2021,NaN,NaN,re,...,Yes,Yes,No,#########,Unknown,No,NaN,No,18-2021,4438965
52,355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,355.0,FHA,NaN,NaN,SURREY,5/4/2021,5/12/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
55,356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,356.0,FHA,NaN,NaN,ABBOTSFORD,5/4/2021,5/27/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
59,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,357.0,FHA,NaN,NaN,SURREY,5/4/2021,5/20/2021,NaN,NaN,tion,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
63,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,358.0,FHA,NaN,NaN,SURREY,5/4/2021,5/14/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,Yes,NaN,No,18-2021,NaN
68,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maintenance/T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [367]:
dfs[1].loc[69:]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
69,359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rades/Construc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,359.0,FHA,NaN,NaN,DELTA,5/4/2021,5/20/2021,NaN,NaN,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,NaN,No,18-2021,18-2021
71,347.0,HAFHA,workplace_names.22(1),workplace_address,cityANGLEY,date_cluster_confirmed_public_health5/3/2021,date_cluster_no_longer_active5/11/2021,earliest_reported_cases,latest_reported_cases,workplace_classificationManufacturing/Industry,...,closure_y_nNo,closed_by_orderNo,voluntary_closureUnknown,closure_date,partially_closedNo,openYes,days_since_last_case,active_clustersNo,cluster_confirmed_epidate18-2021,cluster_closed_epidate
72,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
73,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
74,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,Farm/Agriculture,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
75,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,Manufacturing/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
76,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,None,Unknown,No,55,No,18-2021,None
77,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,Maintenance/Trades/Construction,...,Yes,No,No,None,Yes,No,None,No,18-2021,None
78,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,Farm/Agriculture,...,Yes,Yes,No,#########,Unknown,No,None,No,18-2021,13-4438965
79,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
80,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
81,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
82,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
83,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,Maintenance/Trades/Construction,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

In [309]:
[value for value in dfs[1]['index']]

[179.0,
 180.0,
 181.0,
 182.0,
 183.0,
 184.0,
 185.0,
 186.0,
 187.0,
 188.0,
 189.0,
 190.0,
 191.0,
 192.0,
 193.0,
 194.0,
 195.0,
 196.0,
 197.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 347.0,
 nan,
 nan,
 nan,
 348.0,
 nan,
 nan,
 349.0,
 nan,
 nan,
 nan,
 350.0,
 nan,
 nan,
 nan,
 351.0,
 352.0,
 nan,
 nan,
 nan,
 nan,
 353.0,
 nan,
 354.0,
 nan,
 nan,
 355.0,
 nan,
 nan,
 nan,
 356.0,
 nan,
 nan,
 nan,
 357.0,
 nan,
 nan,
 nan,
 nan,
 358.0,
 nan,
 nan,
 359.0,
 347.0,
 347.0,
 348.0,
 349.0,
 350.0,
 351.0,
 352.0,
 353.0,
 354.0,
 355.0,
 356.0,
 357.0,
 358.0,
 359.0]

In [334]:
dfs[1]['index'].duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
80     True
81     True
82     True
83     True
84     True
Name: index, Length: 85, dtype: bool

## Iteration 3

In [384]:
from tabula import read_pdf
import json
import re

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', column_to_adjust='workplace_name', filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns
                    unparsed_pages[file] = page_number+1
                    print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
                file_dfs.append(
                    merge_rows(df_list[page_number], file) if df_list[page_number]['Unnamed: 0'].isna().sum() > 0 else df_list[page_number]
                    )
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs3, reference3 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs3[1]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......page 1......
	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**
	Removing duplicate rows from F22-1445 Records_Part2.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (13, 23)

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
5,184.0,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
6,185.0,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
7,186.0,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,25,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
8,187.0,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,5,...,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021,NaN
9,188.0,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,4,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
10,189.0,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
11,190.0,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,3,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
12,191.0,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
13,192.0,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,7,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
14,193.0,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
15,194.0,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
16,195.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
17,196.0,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
18,197.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,...,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021,NaN
19,347.0,FHA,None,None,ANGLEY,5/3/2021,5/11/2021,None,None,/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
20,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
21,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
22,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,re,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
23,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
24,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,None,Unknown,No,55,No,18-2021,None
25,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,tion,...,Yes,No,No,None,Yes,No,None,No,18-2021,None
26,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,re,...,Yes,Yes,No,#########,Unknown,No,None,No,18-2021,4438965
27,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
28,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
29,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
30,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
31,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

# Align columns

In [484]:
from tabula import read_pdf
import json
import re

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file, end='...')
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'page {page_number}...', end='...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns
                    unparsed_pages[file] = page_number+1
                    print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
                # Consolidate rows that were incorrectly split
                if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                    df_list[page_number] = merge_rows(df_list[page_number], file)
                # Align the columns
                if value_to_ignore in df_list[page_number].iloc[0].values:
                    value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                    print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                    df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

                # for column in blank_columns:
                #     print('\tShifting columns')
                    # if df_list[page_number][column].isna().sum == 0:
                    #     df_list[page_number][]
                        # shifted_df = df_list[page_number].loc[:,column:].shift(axis=1)
                        # df_list[page_number] = pd.concat([
                        #     df_list[page_number][:column],
                        #     shifted_df
                        # ])
                file_dfs.append(df_list[page_number])
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs1, reference1 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs1[1]

Extracting the following files:
F22-1445 Records_Part1.pdf...page 0......page 1......
	Done
F22-1445 Records_Part2.pdf...page 0......	Removing s.22(1) from column 3
page 1......
	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**
	Removing duplicate rows from F22-1445 Records_Part2.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (13, 23)

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,3,...,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021,15-2021
1,180.0,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,181.0,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,5,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,182.0,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
4,183.0,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,3,...,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN,NaN
5,184.0,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,12,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
6,185.0,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,13,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
7,186.0,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,25,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
8,187.0,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,5,...,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021,NaN
9,188.0,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,4,...,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021,NaN
10,189.0,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
11,190.0,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,3,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
12,191.0,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,11,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
13,192.0,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,7,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
14,193.0,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,4,...,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021,NaN
15,194.0,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,4,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
16,195.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,NaN,...,No,No,NaN,Yes,No,NaN,No,15-2021,NaN,NaN
17,196.0,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,NaN,...,No,No,NaN,No,Yes,NaN,No,15-2021,NaN,NaN
18,197.0,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,NaN,...,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021,NaN
19,347.0,FHA,None,None,ANGLEY,5/3/2021,5/11/2021,None,None,/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
20,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
21,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
22,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,re,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
23,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
24,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,None,Unknown,No,55,No,18-2021,None
25,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,tion,...,Yes,No,No,None,Yes,No,None,No,18-2021,None
26,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,re,...,Yes,Yes,No,#########,Unknown,No,None,No,18-2021,4438965
27,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
28,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
29,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
30,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
31,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

In [428]:
's.22(1)' in dfs1[0].iloc[0].values

False

In [474]:
df = dfs1[1].loc[0].copy()
value_to_ignore = 's.22(1)'
# df.loc[df.eq(value_to_ignore).any(axis=1)]
print(df[df == value_to_ignore].index)
df[df == value_to_ignore]

Index(['workplace_address'], dtype='object')

workplace_address    s.22(1)
Name: 0, dtype: object

In [435]:
dfs1[0].iloc[0].eq('s.22(1)')

index                                   False
HA                                      False
workplace_name                          False
workplace_address                       False
city                                    False
date_cluster_confirmed_public_health    False
date_cluster_no_longer_active           False
earliest_reported_cases                 False
latest_reported_cases                   False
workplace_classification                False
cases_when_cluster_confirmed            False
total_cases                             False
workplace_status                        False
closure_y_n                             False
closed_by_order                         False
voluntary_closure                       False
closure_date                            False
partially_closed                        False
open                                    False
days_since_last_case                    False
cluster_confirmed_epidate               False
cluster_closed_epidate                  False
Name: 0, dtype: bool

In [418]:
dfs1[1].iloc[:,1:] = dfs1[1].iloc[:,:-1]

In [411]:
dfs1[1].shift(axis=1)

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,None,FHA,NaN,s.22(1),ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,None,180,FHA,NaN,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
2,None,181,FHA,NaN,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021
3,None,182,VCH,NaN,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
4,None,183,NHA,NaN,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,...,Yes,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN
5,None,184,FHA,NaN,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
6,None,185,FHA,NaN,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
7,None,186,FHA,NaN,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021
8,None,187,FHA,NaN,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,...,Yes,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021
9,None,188,FHA,NaN,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
10,None,189,VCH,NaN,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
11,None,190,FHA,NaN,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
12,None,191,FHA,NaN,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
13,None,192,FHA,NaN,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
14,None,193,FHA,NaN,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021
15,None,194,FHA,NaN,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
16,None,195,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
17,None,196,VCH,NaN,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,...,No,No,No,NaN,No,Yes,NaN,No,15-2021,NaN
18,None,197,VCH,NaN,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,...,Yes,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021
19,None,347.0,FHA,None,None,ANGLEY,5/3/2021,5/11/2021,None,None,...,transmission,No,No,Unknown,None,No,Yes,None,No,18-2021
20,None,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,...,measures,No,No,Unknown,None,No,Yes,None,No,18-2021
21,None,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,...,Closed,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021
22,None,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,...,measures,No,No,Unknown,None,No,Yes,None,No,18-2021
23,None,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,...,measures,No,No,Unknown,None,No,Yes,None,No,18-2021
24,None,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,...,Closed,Yes,No,Yes,None,Unknown,No,55,No,18-2021
25,None,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,...,PH,Yes,No,No,None,Yes,No,None,No,18-2021
26,None,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,...,order,Yes,Yes,No,#########,Unknown,No,None,No,18-2021
27,None,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,...,Closed,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021
28,None,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,...,measures,No,No,Unknown,None,No,Yes,None,No,18-2021
29,None,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,...,measures,No,No,Unknown,None,No,Yes,None,No,18-2021
30,None,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,...,open,No,No,Unknown,None,No,Yes,None,No,18-2021
31,None,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,...,Closed,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021

In [407]:
's.22(1)' in dfs1[1].loc[0].values

True

In [401]:
dfs1[1][['workplace_name', 'workplace_address']].isna().sum()

workplace_name       32
workplace_address    13
dtype: int64

## Iteration 2: align columns

In [504]:
from tabula import read_pdf
import json
import re

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file)
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'\tpage {page_number}...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns
                    unparsed_pages[file] = page_number+1
                    print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
                # Consolidate rows that were incorrectly split
                if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                    df_list[page_number] = merge_rows(df_list[page_number], file)
                # Align the columns
                if value_to_ignore in df_list[page_number].iloc[0].values:
                    value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                    print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                    df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

                for column in blank_columns:
                    # print('null column:')
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                        # df_list[page_number][]
                        # shifted_df = df_list[page_number].loc[:,column:].shift(axis=1)
                        # df_list[page_number] = pd.concat([
                        #     df_list[page_number][:column],
                        #     shifted_df
                        # ])
                file_dfs.append(df_list[page_number])
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs2, reference2 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs2[1]

Extracting the following files:
F22-1445 Records_Part1.pdf
	page 0...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 1...
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\310562734.py:70: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\310562734.py:70: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

	page 0...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 1...

	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**
	Removing duplicate rows from F22-1445 Records_Part2.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (13, 23)

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\310562734.py:70: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,179.0,FHA,NaN,None,ABBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,Farm/Agricultu\rre,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
1,180.0,FHA,NaN,None,DELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
2,181.0,FHA,NaN,None,PORT\rCOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021
3,182.0,VCH,NaN,None,Vancouver,4/14/2021,NaN,4/14/2021,5/5/2021,Manufacturing\r/Industry,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
4,183.0,NHA,NaN,None,Unknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,...,Yes,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN
5,184.0,FHA,NaN,None,BURNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
6,185.0,FHA,NaN,None,SURREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
7,186.0,FHA,NaN,None,BURNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing\r/Industry,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021
8,187.0,FHA,NaN,None,LANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,...,Yes,Yes,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021
9,188.0,FHA,NaN,None,LANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
10,189.0,VCH,NaN,None,Vancouver,4/15/2021,NaN,4/15/2021,5/1/2021,Office,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
11,190.0,FHA,NaN,None,CHILLIWACK,4/16/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
12,191.0,FHA,NaN,None,LANGLEY,4/16/2021,5/8/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
13,192.0,FHA,NaN,None,DELTA,4/16/2021,4/26/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
14,193.0,FHA,NaN,None,SURREY,4/16/2021,4/30/2021,NaN,NaN,Retail,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021
15,194.0,FHA,NaN,None,BURNABY,4/16/2021,5/6/2021,NaN,NaN,Other,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
16,195.0,VCH,NaN,None,Vancouver,4/16/2021,NaN,4/16/2021,5/1/2021,Office,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
17,196.0,VCH,NaN,None,Richmond,4/16/2021,NaN,4/16/2021,5/4/2021,Other,...,No,No,No,NaN,No,Yes,NaN,No,15-2021,NaN
18,197.0,VCH,NaN,None,Vancouver,4/16/2021,NaN,4/16/2021,5/9/2021,Retail,...,Yes,Yes,No,4/21/2021,No,No,NaN,No,15-2021,16-2021
19,347.0,FHA,None,None,ANGLEY,5/3/2021,5/11/2021,None,None,/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
20,348.0,FHA,None,None,DELTA,5/3/2021,5/12/2021,None,None,Warehouse,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
21,349.0,FHA,None,None,COQUITLAM,5/3/2021,5/19/2021,None,None,tion,...,Yes,Yes,Unknown,5/4/2021,No,No,None,No,18-2021,18-2021
22,350.0,FHA,None,None,MISSION,5/3/2021,5/20/2021,None,None,re,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
23,351.0,FHA,None,None,SURREY,5/3/2021,5/20/2021,None,None,/Industry,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
24,352.0,VIHA,None,None,Victoria,5/3/2021,None,5/1/2021,5/5/2021,Other,...,Yes,No,Yes,None,Unknown,No,55,No,18-2021,None
25,353.0,VCH,None,None,Vancouver,5/3/2021,None,5/3/2021,5/21/2021,tion,...,Yes,No,No,None,Yes,No,None,No,18-2021,None
26,354.0,NHA,None,None,Unknown,5/3/2021,6/15/2021,None,None,re,...,Yes,Yes,No,#########,Unknown,No,None,No,18-2021,4438965
27,355.0,FHA,None,None,SURREY,5/4/2021,5/12/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021
28,356.0,FHA,None,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
29,357.0,FHA,None,None,SURREY,5/4/2021,5/20/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
30,358.0,FHA,None,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,No,18-2021,None
31,359.0,FHA,None,None,DELTA,5/4/2021,5/20/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,No,18-2021,18-2021

In [502]:
dfs2[0]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,workplace_status,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate
0,1,FHA,None,None,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
1,2,FHA,None,None,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
2,3,FHA,None,None,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021
3,4,FHA,None,None,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,Closed,Yes,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021
4,5,FHA,None,None,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021
5,6,FHA,None,None,CHILLIWACK,4/1/2021,4/17/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
6,7,FHA,None,None,COQUITLAM,4/1/2021,4/14/2021,NaN,NaN,Office,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
7,8,FHA,None,None,DELTA,4/1/2021,4/6/2021,NaN,NaN,Transportation,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
8,9,FHA,None,None,LANGLEY,4/1/2021,4/30/2021,NaN,NaN,Farm/Agriculture,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
9,10,FHA,None,None,LANGLEY,4/1/2021,NaN,NaN,NaN,Warehouse,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
10,11,FHA,None,None,MAPLE RIDGE,4/1/2021,4/18/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/6/2021,No,No,NaN,13-2021,14-2021
11,12,FHA,None,None,MISSION,4/1/2021,4/19/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/1/2021,No,No,NaN,13-2021,13-2021
12,13,FHA,None,None,SURREY,4/1/2021,4/23/2021,NaN,NaN,Gym/Fitness,...,NaN,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN
13,14,FHA,None,None,SURREY,4/1/2021,4/14/2021,NaN,NaN,Office,...,Closed,Yes,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021
14,15,FHA,None,None,SURREY,4/1/2021,4/22/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/12/2021,No,No,NaN,13-2021,15-2021
15,16,FHA,None,None,ABBOTSFORD,4/2/2021,4/19/2021,NaN,NaN,Gym/Fitness,...,Closed,Yes,Yes,Unknown,4/3/2021,No,No,NaN,13-2021,13-2021
16,150,FHA,NaN,None,.22(1),BBOTSFORD,4/14/2021,5/3/2021,NaN,NaN,...,3,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021
17,151,FHA,NaN,None,URNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,...,NaN,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN
18,152,FHA,NaN,None,ELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,...,NaN,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN
19,153,FHA,NaN,None,ELTA,4/14/2021,5/9/2021,NaN,NaN,Retail,...,NaN,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN
20,154,FHA,NaN,None,ORT\rOQUITLAM,4/14/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,...,Closed,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021
21,155,FHA,NaN,None,ORT\rOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,Manufacturing/I\rndustry,...,Closed,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021
22,156,FHA,NaN,None,URREY,4/14/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,NaN,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN
23,157,FHA,NaN,None,URREY,4/14/2021,4/27/2021,NaN,NaN,Retail,...,Closed,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021
24,158,FHA,NaN,None,URREY,4/14/2021,4/24/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/15/2021,No,No,NaN,15-2021,15-2021
25,159,FHA,NaN,None,URREY,4/14/2021,4/24/2021,NaN,NaN,Retail,...,Closed,Yes,Yes,Unknown,4/14/2021,No,No,NaN,15-2021,15-2021
26,160,NHA,NaN,None,nknown,4/14/2021,4/29/2021,NaN,NaN,Maintenance/Tr\rades/Constructio\rn,...,Voluntary\rclosure,Yes,No,Yes,NaN,Unknown,No,NaN,15-2021,NaN
27,161,FHA,NaN,None,URNABY,4/15/2021,5/11/2021,NaN,NaN,Manufacturing/I\rndustry,...,Closed,Yes,Yes,Unknown,4/18/2021,No,No,NaN,15-2021,16-2021
28,162,FHA,NaN,None,URNABY,4/15/2021,5/8/2021,NaN,NaN,Transportation,...,Closed,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021
29,163,FHA,NaN,None,ANGLEY,4/15/2021,5/6/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Closed,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021
30,164,FHA,NaN,None,ANGLEY,4/15/2021,4/29/2021,NaN,NaN,Manufacturing/I\rndustry,...,Closed,Yes,Yes,Unknown,4/17/2021,No,No,NaN,15-2021,15-2021
31,165,FHA,NaN,None,URREY,4/15/2021,4/30/2021,NaN,NaN,Gym/Fitness,...,Closed,Yes,Yes,Unknown,4/16/2021,No,No,NaN,15-2021,15-2021
32,166,FHA,NaN,None,URNABY,4/16/2021,5/6/2021,NaN,NaN,Other,...,NaN,No,No,Unknown,NaN,No,No,NaN,15-2021,NaN

## Iteration 3 Join all the documents

In [505]:
from tabula import read_pdf
import json
import re

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file)
        try:
            filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
            path_and_file = filepath+file
            df_list = read_pdf(path_and_file, pages=pages)
            file_dfs = []
            page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
            page1_columns_sorted = sorted(page1_columns)
            for page_number in range(len(df_list)):
                print(f'\tpage {page_number}...')
                df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns
                    unparsed_pages[file] = page_number+1
                    print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
                # Consolidate rows that were incorrectly split
                if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                    df_list[page_number] = merge_rows(df_list[page_number], file)

                # Align the columns
                if value_to_ignore in df_list[page_number].iloc[0].values:
                    value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                    print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                    df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

                for column in blank_columns:
                    # print('null column:')
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None

                file_dfs.append(df_list[page_number])
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)
        except:
            print(f'\nError parsing {file}')
            return dfs_list
        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return pd.concat(dfs_list), reference_dict
    # return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs3, reference3 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs3

Extracting the following files:
F22-1445 Records_Part1.pdf
	page 0...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 1...
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

	page 0...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 1...

	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**
	Removing duplicate rows from F22-1445 Records_Part2.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (13, 23)

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,active_clusters
0,1.0,FHA,None,None,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN
1,2.0,FHA,None,None,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,...,No,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN
2,3.0,FHA,None,None,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Yes,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN
3,4.0,FHA,None,None,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,Yes,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN
4,5.0,FHA,None,None,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Yes,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,355.0,FHA,NaN,None,SURREY,5/4/2021,5/12/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,18-2021,18-2021,No
28,356.0,FHA,NaN,None,ABBOTSFORD,5/4/2021,5/27/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,18-2021,None,No
29,357.0,FHA,NaN,None,SURREY,5/4/2021,5/20/2021,None,None,tion,...,No,No,Unknown,None,No,Yes,None,18-2021,None,No
30,358.0,FHA,NaN,None,SURREY,5/4/2021,5/14/2021,None,None,Retail,...,No,No,Unknown,None,No,Yes,None,18-2021,None,No
31,359.0,FHA,NaN,None,DELTA,5/4/2021,5/20/2021,None,None,tion,...,Yes,Yes,Unknown,5/5/2021,No,No,None,18-2021,18-2021,No

In [506]:
dfs3.columns

Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'active_clusters'],
      dtype='object')

### Process all docs

In [507]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all, reference_all = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
	page 0...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 1...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...

	**Unable to parse columns for page 9 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Shifting data from column 3(workplace_address)
	page 10...

Error parsing F22-1445 Records_Part1.pdf

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\4045601914.py:71: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

ValueError: not enough values to unpack (expected 2, got 0)

## Iteration 4

In [526]:
from tabula import read_pdf
import json
import re

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').to_list()
        page1_columns_sorted = sorted(page1_columns)
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '')
            if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                pass
            else:
                n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns)
                new_columns_padding = ['blank' for padding in range(n_cols_to_pad)]
                df_list[page_number].columns = page1_columns + new_columns_padding
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
            # Consolidate rows that were incorrectly split
            if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                df_list[page_number] = merge_rows(df_list[page_number], file)

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                # print('null column:')
                if df_list[page_number][column].isna().sum() == 0:
                    blank_column_index = df_list[page_number].columns.tolist().index(column)
                    print(f'\tShifting data from column {blank_column_index}({column})')
                    df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                    df_list[page_number].iloc[:,blank_column_index] = None

                file_dfs.append(df_list[page_number])
        final_file_df = pd.concat(file_dfs)
        final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
        final_file_df.reset_index(inplace=True, drop=True)
        final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
        dfs_list.append(final_file_df)

        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')

    return pd.concat(dfs_list), reference_dict
    # return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs4, reference4 = parse_pdf(filenames, pages='1,11', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')
dfs4

Extracting the following files:
F22-1445 Records_Part1.pdf
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...

	**Unable to parse columns for page 2 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

	page 1...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)

	Done
Columns unique to part1: {'blank'}
Columns unique to part2: {'active_clusters'}

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank,active_clusters
0,1,FHA,None,None,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
1,2,FHA,None,None,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,...,No,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN
2,3,FHA,None,None,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Yes,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
3,4,FHA,None,None,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,Yes,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
4,5,FHA,None,None,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Yes,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,371,FHA,NaN,None,ABBOTSFORD,5/5/2021,5/18/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,Yes,Unknown,5/6/2021,No,No,NaN,18-2021,18-2021,NaN,No
66,372,FHA,NaN,None,SURREY,5/5/2021,5/14/2021,NaN,NaN,Food\rProcessing,...,No,Unknown,NaN,No,Yes,NaN,18-2021,NaN,NaN,No
67,373,VIHA,NaN,None,Ladysmith,5/5/2021,NaN,4/29/2021,5/5/2021,Other,...,No,No,NaN,Unknown,Yes,55,18-2021,NaN,NaN,No
68,374,VCH,NaN,None,Richmond,5/5/2021,NaN,5/5/2021,5/20/2021,Maintenance/T\rrades/Construc\rtion,...,No,Yes,NaN,No,No,NaN,18-2021,NaN,NaN,No
69,375,IHA,NaN,None,Nelson,5/6/2021,NaN,5/6/2021,NaN,Health Care\rFacility\r(Acute/LTC),...,No,No,NaN,Unknown,Yes,NaN,18-2021,NaN,NaN,No

In [524]:
dfs4['blank'].unique()

array([nan])

In [525]:
dfs4['active_clusters'].unique()

array([nan, 'No'], dtype=object)

In [520]:
reference4

{'unparsed pages': {'F22-1445 Records_Part1.pdf': 2},
 'unique columns': {'F22-1445 Records_Part2.pdf': 'none'}}

### Process all docs

In [527]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all, reference_all = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...

	**Unable to parse columns for page 9 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 3(workplace_address)
	page 11...

	**Unable to parse columns for page 11 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 12...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...

	**Unable to parse columns for page 13 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

	Shifting data from column 3(workplace_address)
	page 15...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 16...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 17...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 18...

	**Unable to parse columns for page 18 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 19...

	**Unable to parse columns for page 19 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 20...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 21...

	**Unable to parse columns for page 21 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 22...

	**Unable to parse columns for page 22 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 23...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 24...

	**Unable to parse columns for page 24 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 25...

	**Unable to parse columns for page 25 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (14, 22)
		Transformed df shape: (13, 22)
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 26...

	**Unable to parse columns for page 26 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 27...

	**Unable to parse columns for page 27 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 28...

	**Unable to parse columns for page 28 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 29...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 30...

	**Unable to parse columns for page 30 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 31...

	**Unable to parse columns for page 31 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 32...

	**Unable to parse columns for page 32 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

	Shifting data from column 3(workplace_address)
	page 33...

	**Unable to parse columns for page 33 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 34...

	**Unable to parse columns for page 34 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 35...

	**Unable to parse columns for page 35 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 36...

	**Unable to parse columns for page 36 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 37...

	**Unable to parse columns for page 37 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 38...

	**Unable to parse columns for page 38 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 39...

	**Unable to parse columns for page 39 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 40...

	**Unable to parse columns for page 40 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 41...

	**Unable to parse columns for page 41 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 42...

	**Unable to parse columns for page 42 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 43...

	**Unable to parse columns for page 43 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 3(workplace_address)
	page 44...

	**Unable to parse columns for page 44 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 45...

	**Unable to parse columns for page 45 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 46...

	**Unable to parse columns for page 46 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 47...

	**Unable to parse columns for page 47 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 48...

	**Unable to parse columns for page 48 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 49...

	**Unable to parse columns for page 49 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 50...

	**Unable to parse columns for page 50 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 51...

	**Unable to parse columns for page 51 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 52...

	**Unable to parse columns for page 52 of F22-1445 Records_Part1.pdf**
	page 53...

	**Unable to parse columns for page 53 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 54...

	**Unable to parse columns for page 54 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 55...

	**Unable to parse columns for page 55 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

	Shifting data from column 3(workplace_address)
	page 56...

	**Unable to parse columns for page 56 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 57...

	**Unable to parse columns for page 57 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 58...

	**Unable to parse columns for page 58 of F22-1445 Records_Part1.pdf**
	page 59...

	**Unable to parse columns for page 59 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 60...

	**Unable to parse columns for page 60 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 61...

	**Unable to parse columns for page 61 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (39, 23)
		Transformed df shape: (21, 23)
	page 62...

	**Unable to parse columns for page 62 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 63...

	**Unable to parse columns for page 63 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (22, 23)
		Transformed df shape: (21, 23)
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 64...

	**Unable to parse columns for page 64 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (40, 23)
		Transformed df shape: (23, 23)
	page 65...

	**Unable to parse columns for page 65 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 66...

	**Unable to parse columns for page 66 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 67...

	**Unable to parse columns for page 67 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	page 68...

	**Unable to parse columns for page 68 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (34, 23)
		Transformed df shape: (22, 23)
	page 69...

	**Unable to parse columns for page 69 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 70...

	**Unable to parse columns for page 70 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	page 71...

	**Unable to parse columns for page 71 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 72...

	**Unable to parse columns for page 72 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 73...

	**Unable to parse columns for page 73 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

		Transformed df shape: (17, 23)
	page 74...

	**Unable to parse columns for page 74 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 75...

	**Unable to parse columns for page 75 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 76...

	**Unable to parse columns for page 76 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (20, 23)
	page 77...

	**Unable to parse columns for page 77 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 78...

	**Unable to parse columns for page 78 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 79...

	**Unable to parse columns for page 79 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (48, 23)
		Transformed df shape: (20, 23)
	page 80...

	**Unable to parse columns for page 80 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 81...

	**Unable to parse columns for page 81 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (53, 23)
		Transformed df shape: (21, 23)
	page 82...

	**Unable to parse columns for page 82 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 83...

	**Unable to parse columns for page 83 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 84...

	**Unable to parse columns for page 84 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 85...

	**Unable to parse columns for page 85 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 86...

	**Unable to parse columns for page 86 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 87...

	**Unable to parse columns for page 87 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 88...

	**Unable to parse columns for page 88 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 89...

	**Unable to parse columns for page 89 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (54, 23)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

		Transformed df shape: (25, 23)
	page 90...

	**Unable to parse columns for page 90 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 91...

	**Unable to parse columns for page 91 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 92...

	**Unable to parse columns for page 92 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 93...

	**Unable to parse columns for page 93 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 94...

	**Unable to parse columns for page 94 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 95...

	**Unable to parse columns for page 95 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 96...

	**Unable to parse columns for page 96 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 97...

	**Unable to parse columns for page 97 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 98...

	**Unable to parse columns for page 98 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 99...

	**Unable to parse columns for page 99 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 100...

	**Unable to parse columns for page 100 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 101...

	**Unable to parse columns for page 101 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 102...

	**Unable to parse columns for page 102 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 103...

	**Unable to parse columns for page 103 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 104...

	**Unable to parse columns for page 104 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 105...

	**Unable to parse columns for page 105 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 106...

	**Unable to parse columns for page 106 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 107...

	**Unable to parse columns for page 107 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 108...

	**Unable to parse columns for page 108 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (13, 23)
	page 109...

	**Unable to parse columns for page 109 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (51, 25)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

		Transformed df shape: (11, 25)
	page 110...

	**Unable to parse columns for page 110 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (13, 23)
	page 111...

	**Unable to parse columns for page 111 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 112...

	**Unable to parse columns for page 112 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 113...

	**Unable to parse columns for page 113 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (52, 25)
		Transformed df shape: (13, 25)
	page 114...

	**Unable to parse columns for page 114 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 115...

	**Unable to parse columns for page 115 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 116...

	**Unable to parse columns for page 116 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 117...

	**Unable to parse columns for page 117 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 118...

	**Unable to parse columns for page 118 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 119...

	**Unable to parse columns for page 119 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 120...

	**Unable to parse columns for page 120 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 121...

	**Unable to parse columns for page 121 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 122...

	**Unable to parse columns for page 122 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 123...

	**Unable to parse columns for page 123 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 124...

	**Unable to parse columns for page 124 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2782705118.py:75: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

## Iteration 5

In [571]:
from tabula import read_pdf
import json
import re

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        page1_columns_sorted = sorted(page1_columns)
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                pass
            else:
                if len(df_list[page_number].columns) > len(page1_columns):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns)
                    new_columns_padding = ['blank' for padding in range(n_cols_to_pad)]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                elif len(df_list[page_number].columns) < len(page1_columns):
                    df_list[page_number].columns = page1_columns[:len(df_list[page_number].columns)]
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
            # Consolidate rows that were incorrectly split
            if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                df_list[page_number] = merge_rows(df_list[page_number], file)

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        final_file_df = pd.concat(file_dfs)
        final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
        final_file_df.reset_index(inplace=True, drop=True)
        final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
        dfs_list.append(final_file_df)

        print('\n\tDone')
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs5, reference5 = parse_pdf(filenames, pages='124-137', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...

	**Unable to parse columns for page 3 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

number of columns: 23
	page 1...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Shifting data from column 3(workplace_address)
	page 8...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 3(workplace_address)
	page 11...

	**Unable to parse columns for page 11 of F22-1445 Records_Part2.pdf**
	Removing duplicate rows from F22-1445 Records_Part2.pdf...
		Original df shape:  (44, 22)
		Transformed df shape: (15, 22)
	page 12...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to part1: {'blank'}
Columns unique to part2: none

C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values
C:\Users\silvh\AppData\Local\Temp\ipykernel_12316\2970918672.py:79: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values

In [573]:
dfs5

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,blank
0,541.0,NHA,NaN,None,nknown,6/11/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,NaN,Unknow\rn,No,NaN,Yes,23-2021,NaN,NaN
1,542.0,VIHA,NaN,None,ictoria,6/13/2021,NaN,6/10/2021,6/13/2021,Other,...,No,No,NaN,Unknow\rn,Yes,9,Yes,24-2021,NaN,NaN
2,543.0,FHA,NaN,None,BBOTSFORD,6/14/2021,NaN,NaN,NaN,Maintenance/\rTrades/Constr\ruction,...,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN,NaN
3,544.0,FHA,NaN,None,ELTA,6/14/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN,NaN
4,545.0,IHA,NaN,None,elowna,6/15/2021,NaN,6/15/2021,6/20/2021,Manufacturin\rg/Industry,...,Yes,No,6/15/2021,Unknow\rn,No,NaN,Yes,24-2021,24-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,333.0,FHA,None,None,NEW\rWESTMIN\rSTER,4/30/2021,5/4/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,Unknown,NaN,No,Yes,NaN,No,17-2021,NaN,NaN
444,334.0,VIHA,None,None,Nanaimo,4/30/2021,NaN,4/27/2021,4/30/2021,Other,...,No,Yes,NaN,Unknown,No,74.0,No,17-2021,NaN,NaN
445,335.0,VCH,None,None,Richmond,4/30/2021,NaN,4/30/2021,5/19/2021,Office,...,No,No,NaN,No,Yes,NaN,No,17-2021,NaN,NaN
446,336.0,NHA,None,None,Unknown,4/30/2021,5/20/2021,NaN,NaN,Maintenance/Tr\rades/Constructi\ron,...,No,No,NaN,Unknown,No,NaN,No,17-2021,NaN,NaN
447,337.0,FHA,None,None,BURNABY,5/1/2021,5/20/2021,NaN,NaN,Gym/Fitness,...,No,Unknown,NaN,No,Yes,NaN,No,17-2021,NaN,NaN

In [ ]:
reference5

{'unparsed pages': {'F22-1445 Records_Part1.pdf': 9,
  'F22-1445 Records_Part2.pdf': 11},
 'unique columns': {'F22-1445 Records_Part2.pdf': 'none'}}

In [566]:
dfs5.columns.str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)

Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed', 'open',
       'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank', 'workplace_name',
       'workplace_address'],
      dtype='object')

### Process all docs

In [ ]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all, reference_all = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

## Iteration 6

In [593]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for file in pdf_filenames:
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        page1_columns_sorted = sorted(page1_columns)
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                pass
            else:
                if len(df_list[page_number].columns) > len(page1_columns):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns)
                    new_columns_padding = ['blank' for padding in range(n_cols_to_pad)]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                elif len(df_list[page_number].columns) < len(page1_columns):
                    df_list[page_number].columns = page1_columns[:len(df_list[page_number].columns)]
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
            # Consolidate rows that were incorrectly split
            if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                df_list[page_number] = merge_rows(df_list[page_number], file)

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs5, reference5 = parse_pdf(filenames, pages='124', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to part1: none
Columns unique to part2: none

In [588]:
dfs5

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,541,NHA,NaN,None,nknown,6/11/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,No,NaN,Unknow\rn,No,NaN,Yes,23-2021,NaN
1,542,VIHA,NaN,None,ictoria,6/13/2021,NaN,6/10/2021,6/13/2021,Other,...,No,No,No,NaN,Unknow\rn,Yes,9,Yes,24-2021,NaN
2,543,FHA,NaN,None,BBOTSFORD,6/14/2021,NaN,NaN,NaN,Maintenance/\rTrades/Constr\ruction,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
3,544,FHA,NaN,None,ELTA,6/14/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
4,545,IHA,NaN,None,elowna,6/15/2021,NaN,6/15/2021,6/20/2021,Manufacturin\rg/Industry,...,Yes,Yes,No,6/15/2021,Unknow\rn,No,NaN,Yes,24-2021,24-2021
5,546,VIHA,NaN,None,idney,6/15/2021,NaN,6/9/2021,6/16/2021,Maintenance/\rTrades/Constr\ruction,...,No,No,No,NaN,Unknow\rn,Yes,6,Yes,24-2021,NaN
6,547,VIHA,NaN,None,ictoria,6/15/2021,NaN,6/12/2021,6/15/2021,Restaurant/B\rar/Lounge,...,Yes,No,Yes,NaN,Unknow\rn,No,7,Yes,24-2021,NaN
7,541,NHA,NaN,None,nknown,6/11/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,No,NaN,Unknow\rn,No,NaN,Yes,23-2021,NaN
8,542,VIHA,NaN,None,ictoria,6/13/2021,NaN,6/10/2021,6/13/2021,Other,...,No,No,No,NaN,Unknow\rn,Yes,9,Yes,24-2021,NaN
9,543,FHA,NaN,None,BBOTSFORD,6/14/2021,NaN,NaN,NaN,Maintenance/\rTrades/Constr\ruction,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
10,544,FHA,NaN,None,ELTA,6/14/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
11,545,IHA,NaN,None,elowna,6/15/2021,NaN,6/15/2021,6/20/2021,Manufacturin\rg/Industry,...,Yes,Yes,No,6/15/2021,Unknow\rn,No,NaN,Yes,24-2021,24-2021
12,546,VIHA,NaN,None,idney,6/15/2021,NaN,6/9/2021,6/16/2021,Maintenance/\rTrades/Constr\ruction,...,No,No,No,NaN,Unknow\rn,Yes,6,Yes,24-2021,NaN
13,547,VIHA,NaN,None,ictoria,6/15/2021,NaN,6/12/2021,6/15/2021,Restaurant/B\rar/Lounge,...,Yes,No,Yes,NaN,Unknow\rn,No,7,Yes,24-2021,NaN
0,114,FHA,None,None,COQUITLA\rM,4/9/2021,5/2/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
1,115,FHA,None,None,SURREY,4/9/2021,4/21/2021,NaN,NaN,Office,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
2,116,FHA,None,None,ABBOTSFO\rRD,4/9/2021,4/30/2021,NaN,NaN,Manufacturing/\rIndustry,...,Yes,Yes,Unknown,4/10/2021,No,No,NaN,No,14-2021,14-2021
3,117,VCH,None,None,Vancouver,4/9/2021,NaN,4/9/2021,4/30/2021,Other,...,No,No,No,NaN,No,Yes,NaN,No,14-2021,NaN
4,118,VCH,None,None,North\rVancouver,4/9/2021,NaN,4/9/2021,5/7/2021,School/Daycare,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
5,119,FHA,None,None,BURNABY,4/10/2021,4/28/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
6,120,FHA,None,None,DELTA,4/10/2021,4/19/2021,NaN,NaN,Farm/Agricultur\re,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
7,121,VCH,None,None,North\rVancouver,4/10/2021,NaN,4/10/2021,4/25/2021,School/Daycare,...,Yes,No,No,NaN,Yes,No,NaN,No,14-2021,NaN
8,122,VCH,None,None,North\rVancouver,4/10/2021,NaN,4/10/2021,4/28/2021,School/Daycare,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
9,123,VCH,None,None,Vancouver,4/10/2021,NaN,4/10/2021,5/5/2021,School/Daycare,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
10,124,VCH,None,None,West\rVancouver,4/10/2021,NaN,4/10/2021,5/7/2021,Retail,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
11,125,NHA,None,None,Unknown,4/10/2021,4/26/2021,NaN,NaN,Shelter/SRO/Co\rngregate\rHousing,...,No,No,No,NaN,Unknown,No,NaN,No,14-2021,NaN
12,126,FHA,None,None,SURREY,4/11/2021,4/21/2021,NaN,NaN,Personal Care,...,Yes,Yes,Unknown,4/12/2021,No,No,NaN,No,15-2021,15-2021
13,127,FHA,None,None,LANGLEY,4/11/2021,4/11/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
14,128,FHA,None,None,DELTA,4/11/2021,4/14/2021,NaN,NaN,Farm/Agricultur\re,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
15,114,FHA,None,None,COQUITLA\rM,4/9/2021,5/2/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
16,115,FHA,None,None,SURREY,4/9/2021,4/21/2021,NaN,NaN,Office,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
17,116,FHA,None,None,ABBOTSFO\rRD,4/9/2021,4/30/2021,NaN,NaN,Manufacturing/\rIndustry,...,Yes,Yes,Unknown,4/10/2021,No,No,NaN,No,14-2021,14-2021
18,117,VCH,None,None,Vancouver,4/9/2021,NaN,4/9/2021,4/30/2021,Other,...,No,No,No,NaN,No,Yes,NaN,No,14-2021,NaN
19,118,VCH,None,None,North\rVancouver,4/9/2021,NaN,4/9/2021,5/7/2021,School/Daycare,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
20,119,FHA,None,None,BURNABY,4/10/2021,4/28/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
21,120,FHA,None,None,DELTA,4/10/2021,4/19/2021,NaN,NaN,Farm/Agricultur\re,...,No,No,Unknown,NaN,No,No,NaN,No,14-2021,NaN
22,121,VCH,None,None,North\rVancouver,4/10/2021,NaN,4/10/2021,4/25/2021,School/Daycare,...,Yes,No,No,NaN,Yes,No,NaN,No,14-2021,NaN
23,122,VCH,None,None,North\rVancouver,4/10/2021,NaN,4/10/2021,4/28/2021,School/Daycare,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
24,123,VCH,None,None,Vancouver,4/10/2021,NaN,4/10/2021,5/5/2021,School/Daycare,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
25,124,VCH,None,None,West\rVancouver,4/10/2021,NaN,4/10/2021,5/7/2021,Retail,...,Yes,No,Yes,NaN,No,No,NaN,No,14-2021,NaN
26,125,NHA,None,None,Unknown,4/10/2021,4/26/2021,NaN,NaN,Shelter/SRO/Co\rngregate\rHousing,...,No,No,No,NaN,Unknown,No,NaN,No,14-2021,NaN
27,126,FHA,None,None,SURREY,4/11/2021,4/21/2021,NaN,NaN,Personal Care,...,Yes,Yes,Unknown,4/12/2021,No,No,NaN,No,15-2021,15-2021
28,127,FHA,None,None,LANGLEY,4/11/2021,4/11/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
29,128,FHA,None,None,DELTA,4/11/2021,4/14/2021,NaN,NaN,Farm/Agricultur\re,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN

In [583]:
reference5

{'unparsed pages': {},
 'unique columns': {'F22-1445 Records_Part2.pdf': 'none'}}

In [597]:
dfs5b, ref5b = parse_pdf(filenames, pages='136-137', filename=None)

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to part1: none
Columns unique to part2: none

In [596]:
ref5b

{'unparsed pages': {},
 'unique columns': {'F22-1445 Records_Part2.pdf': 'none'}}

In [609]:
dfs5b

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,137,FHA,NaN,None,BURNABY,4/11/2021,4/11/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
1,138,FHA,NaN,None,COQUITLAM,4/11/2021,4/22/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
2,139,FHA,NaN,None,AGASSIZ,4/11/2021,4/27/2021,NaN,NaN,Hospitality/Ser\rvices,...,Yes,Yes,Unknown,4/12/2021,No,No,NaN,No,15-2021,15-2021
3,140,VCH,NaN,None,Vancouver,4/11/2021,NaN,4/11/2021,4/29/2021,Maintenance/T\rrades/Construc\rtion,...,No,No,No,NaN,No,Yes,NaN,No,15-2021,NaN
4,141,NHA,NaN,None,Unknown,4/11/2021,4/26/2021,NaN,NaN,Shelter/SRO/C\rongregate\rHousing,...,No,No,No,NaN,Unknown,No,NaN,No,15-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,333,FHA,None,None,NEW\rWESTMIN\rSTER,4/30/2021,5/4/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,Yes,NaN,No,17-2021,NaN
50,334,VIHA,None,None,Nanaimo,4/30/2021,NaN,4/27/2021,4/30/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,74.0,No,17-2021,NaN
51,335,VCH,None,None,Richmond,4/30/2021,NaN,4/30/2021,5/19/2021,Office,...,No,No,No,NaN,No,Yes,NaN,No,17-2021,NaN
52,336,NHA,None,None,Unknown,4/30/2021,5/20/2021,NaN,NaN,Maintenance/Tr\rades/Constructi\ron,...,No,No,No,NaN,Unknown,No,NaN,No,17-2021,NaN
53,337,FHA,None,None,BURNABY,5/1/2021,5/20/2021,NaN,NaN,Gym/Fitness,...,No,No,Unknown,NaN,No,Yes,NaN,No,17-2021,NaN

In [611]:
[i for i in dfs5b.index]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53]

In [608]:
pd.concat([dfs5b, dfs5b])

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,137,FHA,NaN,None,BURNABY,4/11/2021,4/11/2021,NaN,NaN,Retail,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
1,138,FHA,NaN,None,COQUITLAM,4/11/2021,4/22/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
2,139,FHA,NaN,None,AGASSIZ,4/11/2021,4/27/2021,NaN,NaN,Hospitality/Ser\rvices,...,Yes,Yes,Unknown,4/12/2021,No,No,NaN,No,15-2021,15-2021
3,140,VCH,NaN,None,Vancouver,4/11/2021,NaN,4/11/2021,4/29/2021,Maintenance/T\rrades/Construc\rtion,...,No,No,No,NaN,No,Yes,NaN,No,15-2021,NaN
4,141,NHA,NaN,None,Unknown,4/11/2021,4/26/2021,NaN,NaN,Shelter/SRO/C\rongregate\rHousing,...,No,No,No,NaN,Unknown,No,NaN,No,15-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,333,FHA,NaN,None,NEW\rWESTMIN\rSTER,4/30/2021,5/4/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,Yes,NaN,No,17-2021,NaN
50,334,VIHA,NaN,None,Nanaimo,4/30/2021,NaN,4/27/2021,4/30/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,74.0,No,17-2021,NaN
51,335,VCH,NaN,None,Richmond,4/30/2021,NaN,4/30/2021,5/19/2021,Office,...,No,No,No,NaN,No,Yes,NaN,No,17-2021,NaN
52,336,NHA,NaN,None,Unknown,4/30/2021,5/20/2021,NaN,NaN,Maintenance/Tr\rades/Constructi\ron,...,No,No,No,NaN,Unknown,No,NaN,No,17-2021,NaN
53,337,FHA,NaN,None,BURNABY,5/1/2021,5/20/2021,NaN,NaN,Gym/Fitness,...,No,No,Unknown,NaN,No,Yes,NaN,No,17-2021,NaN

### Process all docs

In [598]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all, reference_all = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 22
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 3(workplace_address)
	page 11...

	**Unable to parse columns for page 11 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 12...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...

	**Unable to parse columns for page 13 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 15...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 16...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 17...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 18...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 19...

	**Unable to parse columns for page 19 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 20...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 21...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 22...

	**Unable to parse columns for page 22 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 23...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 24...

	**Unable to parse columns for page 24 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 25...

	**Unable to parse columns for page 25 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (14, 22)
		Transformed df shape: (13, 22)
	page 26...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 27...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 28...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 29...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 30...

	**Unable to parse columns for page 30 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 31...

	**Unable to parse columns for page 31 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 32...

	**Unable to parse columns for page 32 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 33...

	**Unable to parse columns for page 33 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 34...

	**Unable to parse columns for page 34 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 35...

	**Unable to parse columns for page 35 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 36...

	**Unable to parse columns for page 36 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 37...

	**Unable to parse columns for page 37 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 38...

	**Unable to parse columns for page 38 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 39...

	**Unable to parse columns for page 39 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 40...

	**Unable to parse columns for page 40 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 41...

	**Unable to parse columns for page 41 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 42...

	**Unable to parse columns for page 42 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 43...

	**Unable to parse columns for page 43 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 3(workplace_address)
	page 44...

	**Unable to parse columns for page 44 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 45...

	**Unable to parse columns for page 45 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 46...

	**Unable to parse columns for page 46 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 47...

	**Unable to parse columns for page 47 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 48...

	**Unable to parse columns for page 48 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 49...

	**Unable to parse columns for page 49 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 50...

	**Unable to parse columns for page 50 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 51...

	**Unable to parse columns for page 51 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 52...

	**Unable to parse columns for page 52 of F22-1445 Records_Part1.pdf**
	page 53...

	**Unable to parse columns for page 53 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 54...

	**Unable to parse columns for page 54 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 55...

	**Unable to parse columns for page 55 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 56...

	**Unable to parse columns for page 56 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 57...

	**Unable to parse columns for page 57 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 58...

	**Unable to parse columns for page 58 of F22-1445 Records_Part1.pdf**
	page 59...

	**Unable to parse columns for page 59 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 60...

	**Unable to parse columns for page 60 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 61...

	**Unable to parse columns for page 61 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (39, 23)
		Transformed df shape: (21, 23)
	page 62...

	**Unable to parse columns for page 62 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 63...

	**Unable to parse columns for page 63 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (22, 23)
		Transformed df shape: (21, 23)
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 64...

	**Unable to parse columns for page 64 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (40, 23)
		Transformed df shape: (23, 23)
	page 65...

	**Unable to parse columns for page 65 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 66...

	**Unable to parse columns for page 66 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 67...

	**Unable to parse columns for page 67 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	page 68...

	**Unable to parse columns for page 68 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (34, 23)
		Transformed df shape: (22, 23)
	page 69...

	**Unable to parse columns for page 69 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 70...

	**Unable to parse columns for page 70 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	page 71...

	**Unable to parse columns for page 71 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 72...

	**Unable to parse columns for page 72 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 73...

	**Unable to parse columns for page 73 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (17, 23)
	page 74...

	**Unable to parse columns for page 74 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 75...

	**Unable to parse columns for page 75 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 76...

	**Unable to parse columns for page 76 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (20, 23)
	page 77...

	**Unable to parse columns for page 77 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 78...

	**Unable to parse columns for page 78 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 79...

	**Unable to parse columns for page 79 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (48, 23)
		Transformed df shape: (20, 23)
	page 80...

	**Unable to parse columns for page 80 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 81...

	**Unable to parse columns for page 81 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (53, 23)
		Transformed df shape: (21, 23)
	page 82...

	**Unable to parse columns for page 82 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 83...

	**Unable to parse columns for page 83 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 84...

	**Unable to parse columns for page 84 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 85...

	**Unable to parse columns for page 85 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 86...

	**Unable to parse columns for page 86 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 87...

	**Unable to parse columns for page 87 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 88...

	**Unable to parse columns for page 88 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 89...

	**Unable to parse columns for page 89 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (54, 23)
		Transformed df shape: (25, 23)
	page 90...

	**Unable to parse columns for page 90 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 91...

	**Unable to parse columns for page 91 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 92...

	**Unable to parse columns for page 92 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 93...

	**Unable to parse columns for page 93 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 94...

	**Unable to parse columns for page 94 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 95...

	**Unable to parse columns for page 95 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 96...

	**Unable to parse columns for page 96 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 97...

	**Unable to parse columns for page 97 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 98...

	**Unable to parse columns for page 98 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 99...

	**Unable to parse columns for page 99 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 100...

	**Unable to parse columns for page 100 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 101...

	**Unable to parse columns for page 101 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 102...

	**Unable to parse columns for page 102 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 103...

	**Unable to parse columns for page 103 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 104...

	**Unable to parse columns for page 104 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 105...

	**Unable to parse columns for page 105 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 106...

	**Unable to parse columns for page 106 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 107...

	**Unable to parse columns for page 107 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 108...

	**Unable to parse columns for page 108 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (13, 23)
	page 109...

	**Unable to parse columns for page 109 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (51, 25)
		Transformed df shape: (11, 25)
	page 110...

	**Unable to parse columns for page 110 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (13, 23)
	page 111...

	**Unable to parse columns for page 111 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 112...


In [601]:
dfs_all[-1]

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank
0,158,FHA,None,None,PORT\rCOQUITLAM,4/12/2021,5/14/2021,NaN,NaN,Food\rProcessing,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
1,159,FHA,None,None,ANGLEY,4/12/2021,5/7/2021,NaN,NaN,Retail,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
2,160,VCH,None,None,Vancouver,4/12/2021,NaN,4/12/2021,5/1/2021,Office,...,Yes,No,No,NaN,Yes,No,NaN,No,15-2021,NaN
3,161,NHA,None,None,Unknown,4/12/2021,4/29/2021,NaN,NaN,Manufacturing\r/Industry,...,No,No,No,NaN,Unknown,No,NaN,No,15-2021,NaN
4,162,FHA,None,None,SURREY,4/13/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
5,163,FHA,None,None,SURREY,4/13/2021,5/4/2021,NaN,NaN,Transportation,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
6,164,FHA,None,None,BURNABY,4/13/2021,5/4/2021,NaN,NaN,Gym/Fitness,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021
7,165,FHA,None,None,ABBOTSFORD,4/13/2021,4/28/2021,NaN,NaN,Gym/Fitness,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
8,166,FHA,None,None,DELTA,4/13/2021,5/21/2021,NaN,NaN,Other,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
9,167,FHA,None,None,SURREY,4/13/2021,4/25/2021,NaN,NaN,Maintenance/T\rrades/Construc\rtion,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
10,168,VIHA,None,None,Victoria,4/13/2021,NaN,4/2/2021,4/17/2021,Gym/Fitness,...,Yes,Yes,No,NaN,Unknown,No,73.0,No,15-2021,NaN
11,169,VIHA,None,None,Victoria,4/13/2021,NaN,4/11/2021,4/23/2021,Other,...,Yes,No,Yes,NaN,Unknown,No,67.0,No,15-2021,NaN
12,170,VCH,None,None,Vancouver,4/13/2021,NaN,4/13/2021,5/5/2021,School/Daycar\re,...,Yes,No,No,4/16/2021,Yes,No,NaN,No,15-2021,15-2021
13,171,NHA,None,None,Unknown,4/13/2021,5/6/2021,NaN,NaN,Manufacturing\r/Industry,...,Yes,No,Yes,NaN,Unknown,No,NaN,No,15-2021,NaN
14,172,FHA,None,None,DELTA,4/14/2021,5/19/2021,NaN,NaN,Warehouse,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
15,173,FHA,None,None,SURREY,4/14/2021,5/6/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
16,174,FHA,None,None,SURREY,4/14/2021,4/27/2021,NaN,NaN,Retail,...,Yes,Yes,Unknown,4/16/2021,No,No,NaN,No,15-2021,15-2021
17,175,FHA,None,None,SURREY,4/14/2021,4/24/2021,NaN,NaN,Retail,...,Yes,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021
18,176,FHA,None,None,SURREY,4/14/2021,4/24/2021,NaN,NaN,Restaurant/Bar\r/Lounge,...,Yes,Yes,Unknown,4/15/2021,No,No,NaN,No,15-2021,15-2021
19,177,FHA,None,None,BURNABY,4/14/2021,4/27/2021,NaN,NaN,Transportation,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
20,178,FHA,None,None,PORT\rCOQUITLAM,4/14/2021,4/27/2021,NaN,NaN,Manufacturing\r/Industry,...,Yes,Yes,Unknown,4/18/2021,No,No,NaN,No,15-2021,16-2021

## Iteration 7: Need to exclude pages that don't fit the format

In [605]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for index, file in enumerate(pdf_filenames):
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        page1_columns_sorted = sorted(page1_columns)
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                pass
            else:
                if len(df_list[page_number].columns) > len(page1_columns):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns)
                    new_columns_padding = ['blank' for padding in range(n_cols_to_pad)]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                elif len(df_list[page_number].columns) < len(page1_columns):
                    df_list[page_number].columns = page1_columns[:len(df_list[page_number].columns)]
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
            # Consolidate rows that were incorrectly split
            if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                df_list[page_number] = merge_rows(df_list[page_number], file)

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs7, reference7 = parse_pdf(filenames, pages='124-129', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to part1: none
Columns unique to part2: none

In [606]:
dfs7

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,541,NHA,NaN,None,nknown,6/11/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,No,NaN,Unknow\rn,No,NaN,Yes,23-2021,NaN
1,542,VIHA,NaN,None,ictoria,6/13/2021,NaN,6/10/2021,6/13/2021,Other,...,No,No,No,NaN,Unknow\rn,Yes,9,Yes,24-2021,NaN
2,543,FHA,NaN,None,BBOTSFORD,6/14/2021,NaN,NaN,NaN,Maintenance/\rTrades/Constr\ruction,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
3,544,FHA,NaN,None,ELTA,6/14/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
4,545,IHA,NaN,None,elowna,6/15/2021,NaN,6/15/2021,6/20/2021,Manufacturin\rg/Industry,...,Yes,Yes,No,6/15/2021,Unknow\rn,No,NaN,Yes,24-2021,24-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,208,NHA,None,None,Unknown,4/18/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructi\ron,...,Yes,No,Yes,NaN,Unknown,No,NaN,No,16-2021,NaN
194,209,FHA,None,None,SURREY,4/19/2021,4/20/2021,NaN,NaN,Office,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
195,210,FHA,None,None,SURREY,4/19/2021,4/29/2021,NaN,NaN,Office,...,Yes,No,Unknown,4/21/2021,Yes,No,NaN,No,16-2021,16-2021
196,211,FHA,None,None,BURNABY,4/19/2021,5/7/2021,NaN,NaN,Office,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
197,212,FHA,None,None,SURREY,4/19/2021,5/4/2021,NaN,NaN,Manufacturing/\rIndustry,...,Yes,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021

In [612]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all7, reference_all7 = parse_pdf(filenames, pages='all')
# dfs_all, reference_all = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 22
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 3(workplace_address)
	page 11...

	**Unable to parse columns for page 11 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 12...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...

	**Unable to parse columns for page 13 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 15...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 16...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 17...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 18...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 19...

	**Unable to parse columns for page 19 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 20...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 21...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 22...

	**Unable to parse columns for page 22 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 23...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 24...

	**Unable to parse columns for page 24 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 25...

	**Unable to parse columns for page 25 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (14, 22)
		Transformed df shape: (13, 22)
	page 26...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 27...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 28...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 29...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 30...

	**Unable to parse columns for page 30 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 31...

	**Unable to parse columns for page 31 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 32...

	**Unable to parse columns for page 32 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 33...

	**Unable to parse columns for page 33 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 34...

	**Unable to parse columns for page 34 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 35...

	**Unable to parse columns for page 35 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 36...

	**Unable to parse columns for page 36 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 37...

	**Unable to parse columns for page 37 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 38...

	**Unable to parse columns for page 38 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 39...

	**Unable to parse columns for page 39 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 40...

	**Unable to parse columns for page 40 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 41...

	**Unable to parse columns for page 41 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 42...

	**Unable to parse columns for page 42 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 43...

	**Unable to parse columns for page 43 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 3(workplace_address)
	page 44...

	**Unable to parse columns for page 44 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 45...

	**Unable to parse columns for page 45 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 46...

	**Unable to parse columns for page 46 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 47...

	**Unable to parse columns for page 47 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 48...

	**Unable to parse columns for page 48 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 49...

	**Unable to parse columns for page 49 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 50...

	**Unable to parse columns for page 50 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 51...

	**Unable to parse columns for page 51 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 52...

	**Unable to parse columns for page 52 of F22-1445 Records_Part1.pdf**
	page 53...

	**Unable to parse columns for page 53 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 54...

	**Unable to parse columns for page 54 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 55...

	**Unable to parse columns for page 55 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 56...

	**Unable to parse columns for page 56 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 57...

	**Unable to parse columns for page 57 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 58...

	**Unable to parse columns for page 58 of F22-1445 Records_Part1.pdf**
	page 59...

	**Unable to parse columns for page 59 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 60...

	**Unable to parse columns for page 60 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 61...

	**Unable to parse columns for page 61 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (39, 23)
		Transformed df shape: (21, 23)
	page 62...

	**Unable to parse columns for page 62 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 63...

	**Unable to parse columns for page 63 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (22, 23)
		Transformed df shape: (21, 23)
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 64...

	**Unable to parse columns for page 64 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (40, 23)
		Transformed df shape: (23, 23)
	page 65...

	**Unable to parse columns for page 65 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 66...

	**Unable to parse columns for page 66 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 67...

	**Unable to parse columns for page 67 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	page 68...

	**Unable to parse columns for page 68 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (34, 23)
		Transformed df shape: (22, 23)
	page 69...

	**Unable to parse columns for page 69 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 70...

	**Unable to parse columns for page 70 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	page 71...

	**Unable to parse columns for page 71 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 72...

	**Unable to parse columns for page 72 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 73...

	**Unable to parse columns for page 73 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (17, 23)
	page 74...

	**Unable to parse columns for page 74 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 75...

	**Unable to parse columns for page 75 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 76...

	**Unable to parse columns for page 76 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (52, 23)
		Transformed df shape: (20, 23)
	page 77...

	**Unable to parse columns for page 77 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 78...

	**Unable to parse columns for page 78 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 79...

	**Unable to parse columns for page 79 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (48, 23)
		Transformed df shape: (20, 23)
	page 80...

	**Unable to parse columns for page 80 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 81...

	**Unable to parse columns for page 81 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (53, 23)
		Transformed df shape: (21, 23)
	page 82...

	**Unable to parse columns for page 82 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 83...

	**Unable to parse columns for page 83 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 84...

	**Unable to parse columns for page 84 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 85...

	**Unable to parse columns for page 85 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 86...

	**Unable to parse columns for page 86 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 87...

	**Unable to parse columns for page 87 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 88...

	**Unable to parse columns for page 88 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 89...

	**Unable to parse columns for page 89 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (54, 23)
		Transformed df shape: (25, 23)
	page 90...

	**Unable to parse columns for page 90 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 91...

	**Unable to parse columns for page 91 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 92...

	**Unable to parse columns for page 92 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 93...

	**Unable to parse columns for page 93 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 94...

	**Unable to parse columns for page 94 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 95...

	**Unable to parse columns for page 95 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 96...

	**Unable to parse columns for page 96 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 97...

	**Unable to parse columns for page 97 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 98...

	**Unable to parse columns for page 98 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 99...

	**Unable to parse columns for page 99 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 100...

	**Unable to parse columns for page 100 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 101...

	**Unable to parse columns for page 101 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 102...

	**Unable to parse columns for page 102 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 103...

	**Unable to parse columns for page 103 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 104...

	**Unable to parse columns for page 104 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 105...

	**Unable to parse columns for page 105 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 106...

	**Unable to parse columns for page 106 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 107...

	**Unable to parse columns for page 107 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 108...

	**Unable to parse columns for page 108 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (13, 23)
	page 109...

	**Unable to parse columns for page 109 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (51, 25)
		Transformed df shape: (11, 25)
	page 110...

	**Unable to parse columns for page 110 of F22-1445 Records_Part1.pdf**
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Transformed df shape: (13, 23)
	page 111...

	**Unable to parse columns for page 111 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 112...


In [692]:
print(len(dfs_all7))
pd.concat(dfs_all7, sort=True)

248

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [675]:
dfs_all7[74].iloc[:,-2].unique()

array(['15-2021', nan, '16-2021'], dtype=object)

In [689]:
dfs_all7[74].head()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closed_by_order,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank,blank
0,125,FHA,None,None,BURNABY,4/12/2021,4/20/2021,NaN,NaN,Retail,...,Yes,Unknown,4/13/2021,No,No,NaN,No,15-2021,15-2021,NaN
1,126,FHA,None,None,MISSION,4/12/2021,4/13/2021,NaN,NaN,Farm/Agricult\rure,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,127,FHA,None,None,PORT COQUITLAM,4/12/2021,4/25/2021,NaN,NaN,Restaurant/B\rar/Lounge,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,128,FHA,None,None,SURREY,4/12/2021,4/14/2021,NaN,NaN,Other,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
4,129,FHA,None,None,PORT COQUITLAM,4/12/2021,4/16/2021,NaN,NaN,Manufacturin\rg/Industry,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN

In [669]:
dfs_all7[73].head()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank
0,106,FHA,None,None,PORT COQUITLAM,4/11/2021,4/28/2021,NaN,NaN,Restaurant/B\rar/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
1,107,FHA,None,None,ANGLEY,4/11/2021,4/11/2021,NaN,NaN,Restaurant/B\rar/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
2,108,FHA,None,None,ANGLEY,4/11/2021,4/23/2021,NaN,NaN,Restaurant/B\rar/Lounge,...,No,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN
3,109,FHA,None,None,COQUITLAM,4/11/2021,4/26/2021,NaN,NaN,Restaurant/B\rar/Lounge,...,Yes,Yes,Unknown,4/12/2021,No,No,NaN,No,15-2021,15-2021
4,110,FHA,None,None,ANGLEY,4/11/2021,4/19/2021,NaN,NaN,Office,...,Yes,Yes,Unknown,4/12/2021,No,No,NaN,No,15-2021,15-2021

In [668]:
pd.concat(dfs_all7[:73]).head()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank,Unnamed: 1,Unnamed: 2
0,1.0,FHA,None,None,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN,NaN
1,2.0,FHA,None,None,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,...,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN,NaN
2,3.0,FHA,None,None,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
3,4.0,FHA,None,None,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
4,5.0,FHA,None,None,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN

In [667]:
pd.concat(dfs_all7[:74])

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank,Unnamed: 1,Unnamed: 2
0,1.0,FHA,None,None,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN,NaN
1,2.0,FHA,None,None,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,...,Unknown,NaN,No,No,NaN,13-2021,NaN,NaN,NaN,NaN
2,3.0,FHA,None,None,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Unknown,4/4/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
3,4.0,FHA,None,None,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,Unknown,4/7/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
4,5.0,FHA,None,None,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,Unknown,4/5/2021,No,No,NaN,13-2021,14-2021,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,120.0,FHA,None,None,SURREY,4/12/2021,4/25/2021,NaN,NaN,Transportatio\rn,...,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN,NaN
15,121.0,FHA,None,None,ANGLEY,4/12/2021,5/23/2021,NaN,NaN,Manufacturin\rg/Industry,...,Unknown,4/13/2021,Yes,No,NaN,No,15-2021,15-2021,NaN,NaN
16,122.0,FHA,None,None,SURREY,4/12/2021,4/23/2021,NaN,NaN,Retail,...,Unknown,4/13/2021,No,No,NaN,No,15-2021,15-2021,NaN,NaN
17,123.0,FHA,None,None,CHILLIWACK,4/12/2021,4/23/2021,NaN,NaN,Transportatio\rn,...,Unknown,4/13/2021,No,No,NaN,No,15-2021,15-2021,NaN,NaN
18,124.0,FHA,None,None,DELTA,4/12/2021,5/2/2021,NaN,NaN,Food\rProcessing,...,Unknown,4/17/2021,No,No,NaN,No,15-2021,15-2021,NaN,NaN

In [697]:
dfs_all7[75].head()

,Unnamed: 0,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closed_by_order,voluntary_closure,closure_date,partially_cosed,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank,blank
0,125,FHA,None,None,BURNABY,4/12/2021,4/20/2021,NaN,NaN,Retail,...,Yes,Unknown,4/13/2021,No,No,NaN,No,15-2021,15-2021,NaN
1,126,FHA,None,None,MISSION,4/12/2021,4/13/2021,NaN,NaN,Farm/Agricult\rure,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
2,127,FHA,None,None,PORT COQUITLAM,4/12/2021,4/25/2021,NaN,NaN,Restaurant/B\rar/Lounge,...,Yes,Unknown,4/14/2021,No,No,NaN,No,15-2021,15-2021,NaN
3,128,FHA,None,None,SURREY,4/12/2021,4/14/2021,NaN,NaN,Other,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN
4,129,FHA,None,None,PORT COQUITLAM,4/12/2021,4/16/2021,NaN,NaN,Manufacturin\rg/Industry,...,No,Unknown,NaN,No,No,NaN,No,15-2021,NaN,NaN

In [694]:
pd.concat(dfs_all7[:75], sort=True)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [688]:
print(len(dfs_all7))
[(len(df.columns)) for df in dfs_all7]
# len(set([len(df.columns) for df in dfs_all7]))

248

[22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 23,
 23,
 22,
 22,
 23,
 23,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 23,
 23,
 22,
 22,
 22,
 22,
 23,
 23,
 22,
 22,
 23,
 23,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 24,
 24,
 23,
 23,
 24,
 24,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 24,
 24,
 24,
 24,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 25,
 25,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 25,
 25,
 23,
 23,
 23,
 23,
 23,
 23,
 25,
 25,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23]

## Iteration 8: Return a list for each doc rather than a dataframe

In [707]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    print(f'\t\tOriginal columns:', df.columns)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for index, file in enumerate(pdf_filenames):
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        page1_columns_sorted = sorted(page1_columns)
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                pass
            else:
                if len(df_list[page_number].columns) > len(page1_columns):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns)
                    new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                elif len(df_list[page_number].columns) < len(page1_columns):
                    df_list[page_number].columns = page1_columns[:len(df_list[page_number].columns)]
                else:
                    df_list[page_number].columns = page1_columns
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
            # Consolidate rows that were incorrectly split
            if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                print('Consolidate rows that were incorrectly split: ', df_list[page_number].columns)
                df_list[page_number] = merge_rows(df_list[page_number], file)

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{i+1}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs8, reference8 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 22
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part2.pdf
number of columns: 23
	page 1...
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 2...

	**Unable to parse columns for page 2 of F22-1445 Records_Part2.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed', 'open',
       'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part2.pdf...
		Original df shape:  (52, 23)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed', 'open',
       'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
		Transformed df shape: (13, 23)

	Done
Columns unique to part1: none
Columns unique to part2: {'active_clusters'}

In [699]:
reference8

{'unparsed pages': {},
 'unique columns': {'F22-1445 Records_Part2.pdf': 'none'}}

In [700]:
dfs8

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_y_n,closed_by_order,voluntary_closure,closure_date,partially_closed,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,541,NHA,NaN,None,nknown,6/11/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,No,NaN,Unknow\rn,No,NaN,Yes,23-2021,NaN
1,542,VIHA,NaN,None,ictoria,6/13/2021,NaN,6/10/2021,6/13/2021,Other,...,No,No,No,NaN,Unknow\rn,Yes,9,Yes,24-2021,NaN
2,543,FHA,NaN,None,BBOTSFORD,6/14/2021,NaN,NaN,NaN,Maintenance/\rTrades/Constr\ruction,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
3,544,FHA,NaN,None,ELTA,6/14/2021,NaN,NaN,NaN,Manufacturin\rg/Industry,...,No,No,Unknown,NaN,No,Yes,NaN,Yes,24-2021,NaN
4,545,IHA,NaN,None,elowna,6/15/2021,NaN,6/15/2021,6/20/2021,Manufacturin\rg/Industry,...,Yes,Yes,No,6/15/2021,Unknow\rn,No,NaN,Yes,24-2021,24-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,208,NHA,None,None,Unknown,4/18/2021,5/6/2021,NaN,NaN,Maintenance/Tr\rades/Constructi\ron,...,Yes,No,Yes,NaN,Unknown,No,NaN,No,16-2021,NaN
194,209,FHA,None,None,SURREY,4/19/2021,4/20/2021,NaN,NaN,Office,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
195,210,FHA,None,None,SURREY,4/19/2021,4/29/2021,NaN,NaN,Office,...,Yes,No,Unknown,4/21/2021,Yes,No,NaN,No,16-2021,16-2021
196,211,FHA,None,None,BURNABY,4/19/2021,5/7/2021,NaN,NaN,Office,...,No,No,Unknown,NaN,No,No,NaN,No,16-2021,NaN
197,212,FHA,None,None,SURREY,4/19/2021,5/4/2021,NaN,NaN,Manufacturing/\rIndustry,...,Yes,Yes,Unknown,4/20/2021,No,No,NaN,No,16-2021,16-2021

### Process all docs

In [708]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all8, reference_all8 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 22
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 3(workplace_address)
	page 11...

	**Unable to parse columns for page 11 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 12...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...

	**Unable to parse columns for page 13 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 15...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 16...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 17...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 18...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 19...

	**Unable to parse columns for page 19 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 20...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 21...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 22...

	**Unable to parse columns for page 22 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 23...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 24...

	**Unable to parse columns for page 24 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 25...

	**Unable to parse columns for page 25 of F22-1445 Records_Part1.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (14, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
		Transformed df shape: (13, 22)
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 26...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 27...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 28...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 29...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 30...

	**Unable to parse columns for page 30 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 31...

	**Unable to parse columns for page 31 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 32...

	**Unable to parse columns for page 32 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 33...

	**Unable to parse columns for page 33 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 34...

	**Unable to parse columns for page 34 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 35...

	**Unable to parse columns for page 35 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 36...

	**Unable to parse columns for page 36 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 37...

	**Unable to parse columns for page 37 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 38...

	**Unable to parse columns for page 38 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 39...

	**Unable to parse columns for page 39 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 40...

	**Unable to parse columns for page 40 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 41...

	**Unable to parse columns for page 41 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 42...

	**Unable to parse columns for page 42 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 43...

	**Unable to parse columns for page 43 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 3(workplace_address)
	page 44...

	**Unable to parse columns for page 44 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 45...

	**Unable to parse columns for page 45 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 46...

	**Unable to parse columns for page 46 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 47...

	**Unable to parse columns for page 47 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 48...

	**Unable to parse columns for page 48 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 49...

	**Unable to parse columns for page 49 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 50...

	**Unable to parse columns for page 50 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 51...

	**Unable to parse columns for page 51 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 52...

	**Unable to parse columns for page 52 of F22-1445 Records_Part1.pdf**
	page 53...

	**Unable to parse columns for page 53 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 54...

	**Unable to parse columns for page 54 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 55...

	**Unable to parse columns for page 55 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 56...

	**Unable to parse columns for page 56 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 57...

	**Unable to parse columns for page 57 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 58...

	**Unable to parse columns for page 58 of F22-1445 Records_Part1.pdf**
	page 59...

	**Unable to parse columns for page 59 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 60...

	**Unable to parse columns for page 60 of F22-1445 Records_Part1.pdf**
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 61...

	**Unable to parse columns for page 61 of F22-1445 Records_Part1.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (39, 23)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
		Transformed df shape: (21, 23)
	page 62...

	**Unable to parse columns for page 62 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 63...

	**Unable to parse columns for page 63 of F22-1445 Records_Part1.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (22, 23)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
		Transformed df shape: (21, 23)
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 64...

	**Unable to parse columns for page 64 of F22-1445 Records_Part1.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (40, 23)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
		Transformed df shape: (23, 23)
	page 65...

	**Unable to parse columns for page 65 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 66...

	**Unable to parse columns for page 66 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 67...

	**Unable to parse columns for page 67 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	page 68...

	**Unable to parse columns for page 68 of F22-1445 Records_Part1.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (34, 23)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
		Transformed df shape: (22, 23)
	page 69...

	**Unable to parse columns for page 69 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 70...

	**Unable to parse columns for page 70 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 3
	page 71...

	**Unable to parse columns for page 71 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 72...

	**Unable to parse columns for page 72 of F22-1445 Records_Part1.pdf**
	Shifting data from column 3(workplace_address)
	page 73...

	**Unable to parse columns for page 73 of F22-1445 Records_Part1.pdf**
Consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (49, 23)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
		Transformed df shape: (17, 23)
	page 74...

	**Unable to parse columns for page 74 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 75...

	**Unable to parse columns for page 75 of F22-1445 Records_Part1.pdf**
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)

KeyError: "['HA'] not found in axis"

## Iteration 9: return results if error

In [731]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    print(f'\t\tOriginal columns:', df.columns)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for index, file in enumerate(pdf_filenames):
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        page1_columns_sorted = sorted(page1_columns)
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                pass
            else:
                if len(df_list[page_number].columns) > len(page1_columns):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns)
                    new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                elif len(df_list[page_number].columns) < len(page1_columns):
                    df_list[page_number].columns = page1_columns[:len(df_list[page_number].columns)]
                else:
                    df_list[page_number].columns = page1_columns
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Unable to parse columns for page {page_number+1} of {file}**', sep='')
            # Consolidate rows that were incorrectly split
            if df_list[page_number]['Unnamed: 0'].isna().sum() > 0:
                print('\tAttempting to consolidate rows that were incorrectly split: ', df_list[page_number].columns)
                try:
                    df_list[page_number] = merge_rows(df_list[page_number], file)
                except:
                    previous_columns = dfs_list[index-1].columns
                    print(f'\t\tPrevious df columns:', previous_columns)
                    if len(df_list[page_number].columns) > len(previous_columns):
                        n_cols_to_pad = len(df_list[page_number].columns) - len(previous_columns)
                        new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                        df_list[page_number].columns = page1_columns + new_columns_padding
                    elif len(df_list[page_number].columns) < len(previous_columns):
                        df_list[page_number].columns = previous_columns[:len(df_list[page_number].columns)]
                    else:
                        df_list[page_number].columns = dfs_list[index-1].columns
                    print(f'\t\tCurrent df columns:',df_list[page_number].columns)
                    try:
                        df_list[page_number] = merge_rows(df_list[page_number], file, id_column=['index'])
                        print(f'\t\tSuccessfully consolidated rows on page {page_number+1} of {file}')
                    except:
                        print(f'\t\tUnable to consolidate rows on page {page_number+1} of {file}')
                        reference_dict['unparsed documents'] = file
                        continue

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{pdf_filenames[i]}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
start = 5
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(5,start+n_docs+1)]
dfs8, reference8 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part5.pdf
number of columns: 24
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part6.pdf
number of columns: 22
	page 1...
	Attempting to consolidate rows that were incorrectly split:  Index(['Unnamed: 0', 'Unnamed: 1', 's.22(1)', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (36, 22)
		Original columns: Index(['Unnamed: 0', 'Unnamed: 1', 's.22(1)', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')
		Previous df columns: Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
		Current df columns: Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (36, 22)
		Original columns: Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
		Transformed df shape: (14, 22)
		Successfully consolidated rows on page 1 of F22-1445 Records_Part6.pdf
	Shifting data from column 3(workplace_address)
	page 2...

	**Unable to parse columns for page 2 of F22-1445 Records_Part6.pdf**

	Done
F22-1445 Records_Part7.pdf
number of columns: 24
	page 1...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to partF22-1445 Records_Part5.pdf: none
Columns unique to partF22-1445 Records_Part6.pdf: {'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 2', 'Unnamed: 10', 'Unnamed: 19', 'Unnamed: 11', 's.22(1)', 'Unnamed: 17', 'Unnamed: 20', 'Unnamed: 18', 'Unnamed: 14', 'Unnamed: 6', 'Unnamed: 16', 'Unnamed: 7', 'Unnamed: 12', 'Unnamed: 9', 'Unnamed: 13', 'Unnamed: 15', 'blank0', 'Unnamed: 3', 'Unnamed: 1', 'Unnamed: 8'}
Columns unique to partF22-1445 Records_Part7.pdf: none
Unable to concatenate dataframes from different documents

In [737]:
reference8

{'unparsed pages': {'F22-1445 Records_Part6.pdf': 2},
 'unique columns': {'F22-1445 Records_Part7.pdf': 'none'}}

In [736]:
dfs8[1].columns

Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'index', 'Unnamed: 1', 's.22(1)', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'blank0'],
      dtype='object')

## Iteration 10

In [776]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    print(f'\t\tOriginal columns:', df.columns)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    unparsed_pages = dict()
    for index, file in enumerate(pdf_filenames):
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        if last_id_column in page1_columns:
            page1_columns_sorted = sorted(page1_columns)
        else:
            previous_columns = dfs_list[index-1].columns
            print(f'\t\tNo headers found; using headers from previous document:', previous_columns)
            if len(df_list[page_number].columns) > len(previous_columns):
                n_cols_to_pad = len(df_list[page_number].columns) - len(previous_columns)
                new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                page1_columns_sorted = page1_columns + new_columns_padding
            elif len(df_list[page_number].columns) < len(previous_columns):
                page1_columns_sorted = (previous_columns[:len(df_list[page_number].columns)].to_list())
            else:
                page1_columns_sorted = (dfs_list[index-1].columns.to_list())
            page1_columns_sorted = ['Unnamed: 0' if column=='index' else column for column in page1_columns_sorted]
            print(f'\t\t**Current df columns:',page1_columns_sorted)
        
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            # print('\t\tCurrent number of columns:', len(df_list[page_number].columns), len(page1_columns_sorted))
            if len(df_list[page_number].columns.to_list()) == len(page1_columns_sorted):
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns_sorted
            else:
                if len(df_list[page_number].columns) > len(page1_columns):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns_sorted)
                    new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                elif len(df_list[page_number].columns) < len(page1_columns_sorted):
                    df_list[page_number].columns = page1_columns_sorted[:len(df_list[page_number].columns)]
                else:
                    df_list[page_number].columns = page1_columns_sorted
                unparsed_pages[file] = page_number+1
                print(f'\n\t**Fixing column parsing for page {page_number+1} of {file}**')
                print(f'\t\t{df_list[page_number].columns}')
            # Consolidate rows that were incorrectly split
            if (df_list[page_number]['Unnamed: 0'].isna().sum() > 0):
                # print('\tAttempting to consolidate rows that were incorrectly split: ', df_list[page_number].columns)
                print('\tAttempting to consolidate rows that were incorrectly split: ')
                try:
                    df_list[page_number] = merge_rows(df_list[page_number], file)
                except:
                    # try:
                    #     df_list[page_number] = merge_rows(df_list[page_number], file, id_column=['index'])
                    #     print(f'\t\tSuccessfully consolidated rows on page {page_number+1} of {file}')
                    # except:
                    print(f'\t\tUnable to consolidate rows on page {page_number+1} of {file}')
                    reference_dict['unparsed documents'] = file
                    continue

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{pdf_filenames[i]}: {unique_cols_dict[file]}')
    reference_dict['unparsed pages'] = unparsed_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
start = 5
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(start,start+n_docs)]
dfs10, reference10 = parse_pdf(filenames, pages='1,10', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part5.pdf
number of columns: 24
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
F22-1445 Records_Part6.pdf
number of columns: 22
		No headers found; using headers from previous document: Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
		**Current df columns: ['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city', 'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active', 'earliest_reported_cases', 'latest_reported_cases', 'workplace_classification', 'cases_when_cluster_confirmed', 'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order', 'voluntary_closure', 'closure_date', 'partially_closed', 'unknown_closure_type', 'open', 'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate']
	page 1...

	**Fixing column parsing for page 1 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (36, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
		Transformed df shape: (14, 22)
	Shifting data from column 3(workplace_address)
	page 2...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to partF22-1445 Records_Part5.pdf: {'cluster_closed_epidate'}
Columns unique to partF22-1445 Records_Part6.pdf: none

In [777]:
reference10

{'unparsed pages': {'F22-1445 Records_Part6.pdf': 1},
 'unique columns': {'F22-1445 Records_Part6.pdf': 'none'}}

In [778]:
dfs10

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closed_by_order,voluntary_closure,closure_date,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate
0,753.0,VIHA,None,None,Victoria,9/8/2021,NaN,8/5/2021,9/8/2021,Restaurant/Bar/\rLounge,...,No,No,NaN,Unknown,No,Yes,34.0,No,36-2021,NaN
1,754.0,VIHA,None,None,Nanaimo,9/8/2021,NaN,8/31/2021,9/8/2021,Manufacturing/I\rndustry,...,No,No,NaN,Unknown,No,Yes,34.0,No,36-2021,NaN
2,755.0,VIHA,None,None,ake Cowichan,9/8/2021,NaN,9/6/2021,9/8/2021,Restaurant/Bar/\rLounge,...,No,No,NaN,Unknown,No,Yes,34.0,No,36-2021,NaN
3,756.0,NHA,None,None,Unknown,9/8/2021,9/23/2021,NaN,NaN,Manufacturing/I\rndustry,...,No,Yes,9/8/2021,Unknown,No,No,NaN,No,36-2021,36-2021
4,757.0,NHA,None,None,Unknown,9/8/2021,9/21/2021,NaN,NaN,School/Daycare,...,No,No,NaN,Unknown,No,No,NaN,No,36-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,149.0,FHA,None,None,SURREY,4/12/2021,4/24/2021,NaN,NaN,Office,...,Yes,Unknown,4/14/2021,No,No,Yes,NaN,No,15-2021,NaN
52,150.0,FHA,None,None,CHILLIWA\rCK,4/12/2021,4/23/2021,NaN,NaN,Transportatio\rn,...,Yes,Unknown,4/13/2021,No,No,Yes,NaN,No,15-2021,NaN
53,151.0,FHA,None,None,SURREY,4/12/2021,4/23/2021,NaN,NaN,Retail,...,Yes,Unknown,4/13/2021,No,No,Yes,NaN,No,15-2021,NaN
54,152.0,FHA,None,None,BURNABY,4/12/2021,4/22/2021,NaN,NaN,Office,...,No,Unknown,4/13/2021,Yes,No,Yes,NaN,No,15-2021,NaN
55,153.0,FHA,None,None,BURNABY,4/12/2021,4/20/2021,NaN,NaN,Retail,...,Yes,Unknown,4/13/2021,No,No,Yes,NaN,No,15-2021,NaN

### Process all docs

In [779]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all10, reference_all10 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 22
	page 1...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
	Shifting data from column 3(workplace_address)
	page 11...

	**Fixing column parsing for page 11 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 12...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...

	**Fixing column parsing for page 13 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 15...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 16...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 17...
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 18...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 19...

	**Fixing column parsing for page 19 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 20...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 21...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 22...

	**Fixing column parsing for page 22 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 23...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 24...

	**Fixing column parsing for page 24 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 25...
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (14, 22)
		Original columns: Index(['HA', 'Unnamed: 0', 'cases_when_cluster_confirmed', 'city',
       'closed_by_order', 'closure_date', 'closure_y_n',
       'cluster_closed_epidate', 'cluster_confirmed_epidate',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'days_since_last_case', 'earliest_reported_cases',
       'latest_reported_cases', 'open', 'partially_cosed', 'total_cases',
       'voluntary_closure', 'workplace_address', 'workplace_classification',
       'workplace_name', 'workplace_status'],
      dtype='object')
		Transformed df shape: (13, 22)
	Shifting data from column 18(workplace_address)
	page 26...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 27...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 28...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 29...
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 30...

	**Fixing column parsing for page 30 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 31...

	**Fixing column parsing for page 31 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 32...

	**Fixing column parsing for page 32 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 33...

	**Fixing column parsing for page 33 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 34...

	**Fixing column parsing for page 34 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 35...

	**Fixing column parsing for page 35 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 36...

	**Fixing column parsing for page 36 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 37...

	**Fixing column parsing for page 37 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 38...

	**Fixing column parsing for page 38 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 39...

	**Fixing column parsing for page 39 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 40...

	**Fixing column parsing for page 40 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 41...

	**Fixing column parsing for page 41 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 42...

	**Fixing column parsing for page 42 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 43...

	**Fixing column parsing for page 43 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 3(workplace_address)
	page 44...

	**Fixing column parsing for page 44 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 45...

	**Fixing column parsing for page 45 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 46...

	**Fixing column parsing for page 46 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',

ValueError: Length mismatch: Expected axis has 23 elements, new values have 22 elements

## Iteration 11

In [821]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    print(f'\t\tOriginal columns:', df.columns)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    corrected_pages = dict()
    for index, file in enumerate(pdf_filenames):
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        if last_id_column in page1_columns:
            page1_columns_sorted = sorted(page1_columns)
        else:
            previous_columns = dfs_list[index-1].columns
            print(f'\t\tNo headers found; using headers from previous document:', previous_columns)
            if len(df_list[page_number].columns) > len(previous_columns):
                n_cols_to_pad = len(df_list[page_number].columns) - len(previous_columns)
                new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                page1_columns += new_columns_padding
                page1_columns_sorted = page1_columns + new_columns_padding
            elif len(df_list[page_number].columns) < len(previous_columns):
                page1_columns_sorted = (previous_columns[:len(df_list[page_number].columns)].to_list())
                page1_columns += new_columns_padding
            else:
                page1_columns_sorted = (dfs_list[index-1].columns.to_list())
            page1_columns_sorted = ['Unnamed: 0' if column=='index' else column for column in page1_columns_sorted]
            print(f'\t\t**Current df columns:',page1_columns_sorted)
        
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            print('\t\tCurrent number of columns:', len(df_list[page_number].columns), len(page1_columns_sorted))
            if len(df_list[page_number].columns.to_list()) == len(page1_columns_sorted):
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns_sorted
                    print('\t\tKeeping page 1 columns')
            else:
                if len(df_list[page_number].columns) > len(page1_columns_sorted):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns_sorted)
                    new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                    df_list[page_number].columns = page1_columns_sorted + new_columns_padding
                    print('\t\tPadding columns')
                elif len(df_list[page_number].columns) < len(page1_columns_sorted):
                    df_list[page_number].columns = page1_columns_sorted[:len(df_list[page_number].columns)]
                    print('\t\tDropping columns')
                else:
                    df_list[page_number].columns = page1_columns_sorted
                # if len(df_list[page_number].columns) > len(page1_columns):
                #     n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns_sorted)
                #     new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                #     df_list[page_number].columns = page1_columns_sorted + new_columns_padding
                # elif len(df_list[page_number].columns) < len(page1_columns_sorted):
                #     df_list[page_number].columns = page1_columns_sorted[:len(df_list[page_number].columns)]
                # else:
                #     df_list[page_number].columns = page1_columns_sorted
                corrected_pages[file] = page_number+1
                print(f'\n\t**Fixing column parsing for page {page_number+1} of {file}**')
                print(f'\t\t{df_list[page_number].columns}')
            # Consolidate rows that were incorrectly split
            if (df_list[page_number]['Unnamed: 0'].isna().sum() > 0):
                # print('\tAttempting to consolidate rows that were incorrectly split: ', df_list[page_number].columns)
                print('\tAttempting to consolidate rows that were incorrectly split: ')
                try:
                    df_list[page_number] = merge_rows(df_list[page_number], file)
                except:
                    # try:
                    #     df_list[page_number] = merge_rows(df_list[page_number], file, id_column=['index'])
                    #     print(f'\t\tSuccessfully consolidated rows on page {page_number+1} of {file}')
                    # except:
                    print(f'\t\tUnable to consolidate rows on page {page_number+1} of {file}')
                    reference_dict['unparsed documents'] = file
                    continue

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{pdf_filenames[i]}: {unique_cols_dict[file]}')
    reference_dict['corrected pages'] = corrected_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
start = 5
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(start,start+n_docs)]
dfs11, reference11 = parse_pdf(filenames, pages='1-6', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part5.pdf
number of columns: 24
	page 1...
		Current number of columns: 24 24
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
		Current number of columns: 24 24
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
		Current number of columns: 24 24
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
		Current number of columns: 26 24
		Padding columns

	**Fixing column parsing for page 4 of F22-1445 Records_Part5.pdf**
		Index(['HA', 'Unnamed: 0', 'active_clusters', 'cases_when_cluster_confirmed',
       'city', 'closed_by_order', 'closure_date', 'closure_y_n',
       'cluster_closed_epidate', 'cluster_confirmed_epidate',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'days_since_last_case', 'earliest_reported_cases',
       'latest_reported_cases', 'open', 'partially_closed', 'total_cases',
       'unknown_closure_type', 'voluntary_closure', 'workplace_address',
       'workplace_classification', 'workplace_name', 'workplace_status',
       'blank0', 'blank1'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part5.pdf...
		Original df shape:  (4, 26)
		Original columns: Index(['HA', 'Unnamed: 0', 'active_clusters', 'cases_when_cluster_confirmed',
       'city', 'closed_by_order', 'closure_date', 'closure_y_n',
       'cluster_closed_epidate', 'cluster_confirmed_epidate',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'days_since_last_case', 'earliest_reported_cases',
       'latest_reported_cases', 'open', 'partially_closed', 'total_cases',
       'unknown_closure_type', 'voluntary_closure', 'workplace_address',
       'workplace_classification', 'workplace_name', 'workplace_status',
       'blank0', 'blank1'],
      dtype='object')
		Transformed df shape: (1, 26)
	Shifting data from column 20(workplace_address)

	Done
F22-1445 Records_Part6.pdf
number of columns: 22
		No headers found; using headers from previous document: Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1'],
      dtype='object')
		**Current df columns: ['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city', 'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active', 'earliest_reported_cases', 'latest_reported_cases', 'workplace_classification', 'cases_when_cluster_confirmed', 'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order', 'voluntary_closure', 'closure_date', 'partially_closed', 'unknown_closure_type', 'open', 'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate']
	page 1...
		Current number of columns: 22 23
		Dropping columns

	**Fixing column parsing for page 1 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (36, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
		Transformed df shape: (14, 22)
	Shifting data from column 3(workplace_address)
	page 2...
		Current number of columns: 24 23
		Padding columns

	**Fixing column parsing for page 2 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate', 'blank0'],
      dtype='object')
	Shifting data from column 3(workplace_address)
	page 3...
		Current number of columns: 20 23
		Dropping columns

	**Fixing column parsing for page 3 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (23, 20)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open'],
      dtype='object')
		Transformed df shape: (14, 20)
	Shifting data from column 3(workplace_address)
	page 4...
		Current number of columns: 23 23
		Keeping page 1 columns
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
		Current number of columns: 22 23
		Dropping columns

	**Fixing column parsing for page 5 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (35, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
		Transformed df shape: (14, 22)
	Shifting data from column 3(workplace_address)
	page 6...
		Current number of columns: 23 23
		Keeping page 1 columns
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to partF22-1445 Records_Part5.pdf: {'cluster_closed_epidate', 'blank1'}
Columns unique to partF22-1445 Records_Part6.pdf: none

In [822]:
reference11

{'corrected pages': {'F22-1445 Records_Part5.pdf': 4,
  'F22-1445 Records_Part6.pdf': 5},
 'unique columns': {'F22-1445 Records_Part6.pdf': 'none'}}

In [823]:
dfs11

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_date,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,blank0,blank1
0,753,VIHA,None,None,Victoria,9/8/2021,NaN,8/5/2021,9/8/2021,Restaurant/Bar/\rLounge,...,NaN,Unknown,No,Yes,34.0,No,36-2021,NaN,NaN,NaN
1,754,VIHA,None,None,Nanaimo,9/8/2021,NaN,8/31/2021,9/8/2021,Manufacturing/I\rndustry,...,NaN,Unknown,No,Yes,34.0,No,36-2021,NaN,NaN,NaN
2,755,VIHA,None,None,ake Cowichan,9/8/2021,NaN,9/6/2021,9/8/2021,Restaurant/Bar/\rLounge,...,NaN,Unknown,No,Yes,34.0,No,36-2021,NaN,NaN,NaN
3,756,NHA,None,None,Unknown,9/8/2021,9/23/2021,NaN,NaN,Manufacturing/I\rndustry,...,9/8/2021,Unknown,No,No,NaN,No,36-2021,36-2021,NaN,NaN
4,757,NHA,None,None,Unknown,9/8/2021,9/21/2021,NaN,NaN,School/Daycare,...,NaN,Unknown,No,No,NaN,No,36-2021,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,92.0,NHA,None,None,nknown,4/7/2021,6/9/2021,NaN,NaN,Manufacturin\rg/Industry,...,NaN,Unknown,No,No,NaN,No,14-2021,NaN,NaN,NaN
156,93.0,FHA,None,None,ORT\rOODY,4/8/2021,6/17/2021,NaN,NaN,Gym/Fitness,...,4/14/2021,No,No,Yes,NaN,No,14-2021,NaN,NaN,NaN
157,94.0,FHA,None,None,URREY,4/8/2021,5/15/2021,NaN,NaN,Gym/Fitness,...,4/12/2021,No,No,Yes,NaN,No,14-2021,NaN,NaN,NaN
158,95.0,FHA,None,None,URNABY,4/8/2021,5/11/2021,NaN,NaN,Gym/Fitness,...,5/2/2021,No,No,Yes,NaN,No,14-2021,NaN,NaN,NaN
159,96.0,FHA,None,None,URREY,4/8/2021,4/29/2021,NaN,NaN,Office,...,4/18/2021,Yes,No,Yes,NaN,No,14-2021,NaN,NaN,NaN

In [825]:
dfs11['blank0'].unique()

array([nan, 'Yes', '14-2021', '16-2021'], dtype=object)

In [826]:
dfs11[~dfs11['blank0'].isna()]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,closure_date,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,blank0,blank1
128,NHA,817.0,No,None,None,None,ndustry,3,None,No,...,Unknown,No,None,No,3,None,None,None,Yes,40-2021
129,NHA,817.0,No,None,None,None,ndustry,3,None,No,...,Unknown,No,None,No,3,None,None,None,Yes,40-2021
29,30.0,FHA,None,None,DELTA,4/4/2021,4/16/2021,NaN,NaN,Restaurant/Ba\rr/Lounge,...,4/7/2021,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN
30,31.0,FHA,None,None,SURREY,4/4/2021,4/16/2021,NaN,NaN,Retail,...,4/8/2021,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN
31,32.0,FHA,None,None,SURREY,4/4/2021,4/10/2021,NaN,NaN,Office,...,4/4/2021,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN
32,33.0,VCH,None,None,North\rVancouver,4/4/2021,NaN,4/4/2021,5/15/2021,Maintenance/\rTrades/Constr\ruction,...,4/21/2021,No,No,No,NaN,No,14-2021,NaN,16-2021,NaN
41,30.0,FHA,None,None,DELTA,4/4/2021,4/16/2021,NaN,NaN,Restaurant/Ba\rr/Lounge,...,4/7/2021,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN
42,31.0,FHA,None,None,SURREY,4/4/2021,4/16/2021,NaN,NaN,Retail,...,4/8/2021,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN
43,32.0,FHA,None,None,SURREY,4/4/2021,4/10/2021,NaN,NaN,Office,...,4/4/2021,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN
44,33.0,VCH,None,None,North\rVancouver,4/4/2021,NaN,4/4/2021,5/15/2021,Maintenance/\rTrades/Constr\ruction,...,4/21/2021,No,No,No,NaN,No,14-2021,NaN,16-2021,NaN

## Iteration 12: indicate document name

In [845]:
from tabula import read_pdf
import json
import re
import warnings
warnings.simplefilter("ignore", category=FutureWarning)

def merge_rows(df, file, id_column=['Unnamed: 0'], fill_method='bfill', groupby_column=['HA']):
    """
    Merges rows in a pandas dataframe that were parsed incorrectly into multiple rows.
    Assumes that the rows that need to be merged have the same value in a unique ID column.
    """
    print(f'\tRemoving duplicate rows from {file}...')
    print('\t\tOriginal df shape: ', df.shape)
    print(f'\t\tOriginal columns:', df.columns)
    df[id_column] = df[id_column].fillna(method=fill_method)
    
    # Group the rows by the unique ID column and aggregate the values in each group

    columns_to_fill = df.drop(columns=groupby_column).columns
    grouped_df = df.groupby(id_column+groupby_column, as_index=False).agg(
        lambda x: ''.join(str(v) for v in x if (type(v)==str) & (x.name in columns_to_fill)))
    grouped_df = grouped_df[grouped_df[groupby_column[0]] != groupby_column[0]]
    # Return the merged dataframe
    print('\t\tTransformed df shape:', grouped_df.shape)
    return grouped_df.replace('', None)

def parse_pdf(pdf_filenames, filepath=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\raw', 
    pages='all', last_id_column='HA', value_to_ignore='s.22(1)',
    blank_columns=['workplace_name', 'workplace_address'],
    filename=None,
    path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'):
    """
    Create dataframe from a PDF file using 
    """
    print(f'Extracting the following files:')
    if type(pdf_filenames) != list:
        pdf_filenames = [pdf_filenames]
    dfs_list = []
    reference_dict = dict()
    corrected_pages = dict()
    for index, file in enumerate(pdf_filenames):
        print(file)
        filepath = f'{filepath}/'.replace('\\','/') if filepath else ''
        path_and_file = filepath+file
        try:
            df_list = read_pdf(path_and_file, pages=pages)
        except:
            print(f'\nError parsing {file}')
        file_dfs = []
        page1_columns = df_list[0].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True).to_list()
        print('number of columns:', len(page1_columns))
        if last_id_column in page1_columns:
            page1_columns_sorted = sorted(page1_columns)
        else:
            previous_columns = dfs_list[index-1].columns
            print(f'\t\tNo headers found; using headers from previous document:', previous_columns)
            if len(df_list[page_number].columns) > len(previous_columns):
                n_cols_to_pad = len(df_list[page_number].columns) - len(previous_columns)
                new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                page1_columns_sorted = sorted(page1_columns) + new_columns_padding
                page1_columns = page1_columns + new_columns_padding

            elif len(df_list[page_number].columns) < len(previous_columns):
                page1_columns = (previous_columns[:len(df_list[page_number].columns)].to_list())
                page1_columns_sorted = sorted(page1_columns)
            else:
                page1_columns_sorted = (dfs_list[index-1].columns.to_list())
            page1_columns = ['Unnamed: 0' if column=='index' else column for column in page1_columns]
            print(f'\t\t**Current df columns:',page1_columns)
        
        for page_number in range(len(df_list)):
            print(f'\tpage {page_number+1}...')
            df_list[page_number].columns = df_list[page_number].columns.str.replace('\r', '').str.replace(r'(workplace)([a-zA-Z]+)', r'\1_\2', regex=True)
            print('\t\tCurrent number of columns:', len(df_list[page_number].columns), len(page1_columns_sorted))
            print(f'\t\t{len(page1_columns_sorted)}, {len(page1_columns)}')
            if len(df_list[page_number].columns.to_list()) == len(page1_columns_sorted):
                if sorted(df_list[page_number].columns.to_list()) == page1_columns_sorted:
                    pass
                else:
                    df_list[page_number].columns = page1_columns 
                    print('\t\tKeeping page 1 columns')
            else:
                if len(df_list[page_number].columns) > len(page1_columns_sorted):
                    n_cols_to_pad = len(df_list[page_number].columns) - len(page1_columns_sorted)
                    new_columns_padding = [f'blank{index}' for index, col in enumerate(range(n_cols_to_pad))]
                    df_list[page_number].columns = page1_columns + new_columns_padding
                    print('\t\tPadding columns')
                elif len(df_list[page_number].columns) < len(page1_columns_sorted):
                    df_list[page_number].columns = page1_columns[:len(df_list[page_number].columns)]
                    print('\t\tDropping columns')
                else:
                    df_list[page_number].columns = page1_columns
                corrected_pages[file] = page_number+1
                print(f'\n\t**Fixing column parsing for page {page_number+1} of {file}**')
                print(f'\t\t{df_list[page_number].columns}')
            # Consolidate rows that were incorrectly split
            if (df_list[page_number]['Unnamed: 0'].isna().sum() > 0):
                # print('\tAttempting to consolidate rows that were incorrectly split: ', df_list[page_number].columns)
                print('\tAttempting to consolidate rows that were incorrectly split: ')
                try:
                    df_list[page_number] = merge_rows(df_list[page_number], file)
                except:
                    print(f'\t\tUnable to consolidate rows on page {page_number+1} of {file}')
                    reference_dict['unparsed documents'] = file
                    continue

            # Align the columns
            if value_to_ignore in df_list[page_number].iloc[0].values:
                value_to_ignore_column = df_list[page_number].iloc[0].values.tolist().index(value_to_ignore)
                print(f'\tRemoving {value_to_ignore} from column {value_to_ignore_column}')
                df_list[page_number].iloc[0, value_to_ignore_column:-1] = df_list[page_number].iloc[0, value_to_ignore_column+1:].values

            for column in blank_columns:
                try:
                    if df_list[page_number][column].isna().sum() == 0:
                        blank_column_index = df_list[page_number].columns.tolist().index(column)
                        print(f'\tShifting data from column {blank_column_index}({column})')
                        df_list[page_number].iloc[:,blank_column_index+1:] = df_list[page_number].iloc[:,blank_column_index:-1].values 
                        df_list[page_number].iloc[:,blank_column_index] = None
                except:
                    pass

                file_dfs.append(df_list[page_number])
        
        try:
            final_file_df = pd.concat(file_dfs)
            final_file_df['file'] = file
            final_file_df.columns = final_file_df.columns.str.replace('cosed', 'closed')
            final_file_df.reset_index(inplace=True, drop=True)
            final_file_df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
            dfs_list.append(final_file_df)

            print('\n\tDone')
        except:
            print(f'Error concatenating dataframes from {file}')
            return file_dfs, {file: 'DataFrame concatenation error'}
    unique_cols_dict = {}
    for i, df in enumerate(dfs_list):
        other_dfs = dfs_list[:i] + dfs_list[i+1:]
        other_cols = set().union(*[set(other_df.columns) for other_df in other_dfs])
        unique_columns = set(df.columns) - other_cols
        unique_cols_dict[file] = unique_columns if len(unique_columns)>0 else "none"
        print(f'Columns unique to part{pdf_filenames[i]}: {unique_cols_dict[file]}')
    reference_dict['corrected pages'] = corrected_pages
    reference_dict['unique columns'] = unique_cols_dict
    if filename:
        try:
            savepickle(dfs_list, filename=filename, path=path)
            with open(f'{filepath}{filename}_reference.json','w') as json_file:
                json.dump(reference_dict, json_file)
        except:
            print('Unable to save outputs')
    try:
        return pd.concat(dfs_list), reference_dict
    except:
        print('Unable to concatenate dataframes from different documents')
        return dfs_list, reference_dict

n_docs = 2
start = 5
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(start,start+n_docs)]
dfs12, reference12 = parse_pdf(filenames, pages='1-6', filename=None)
# dfs4, reference4 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')
# dfs, unique_cols = parse_pdf(filenames, pages='1-2', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part5.pdf
number of columns: 24
	page 1...
		Current number of columns: 24 24
		24, 24
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
		Current number of columns: 24 24
		24, 24
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
		Current number of columns: 24 24
		24, 24
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
		Current number of columns: 26 24
		24, 24
		Padding columns

	**Fixing column parsing for page 4 of F22-1445 Records_Part5.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part5.pdf...
		Original df shape:  (4, 26)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1'],
      dtype='object')
		Transformed df shape: (1, 26)

	Done
F22-1445 Records_Part6.pdf
number of columns: 22
		No headers found; using headers from previous document: Index(['index', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1', 'file'],
      dtype='object')
		**Current df columns: ['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city', 'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active', 'earliest_reported_cases', 'latest_reported_cases', 'workplace_classification', 'cases_when_cluster_confirmed', 'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order', 'voluntary_closure', 'closure_date', 'partially_closed', 'unknown_closure_type', 'open', 'days_since_last_case', 'active_clusters', 'cluster_confirmed_epidate']
	page 1...
		Current number of columns: 22 23
		23, 23
		Dropping columns

	**Fixing column parsing for page 1 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (36, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
		Transformed df shape: (14, 22)
	Shifting data from column 3(workplace_address)
	page 2...
		Current number of columns: 24 23
		23, 23
		Padding columns

	**Fixing column parsing for page 2 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters', 'cluster_confirmed_epidate', 'blank0'],
      dtype='object')
	Shifting data from column 3(workplace_address)
	page 3...
		Current number of columns: 20 23
		23, 23
		Dropping columns

	**Fixing column parsing for page 3 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (23, 20)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open'],
      dtype='object')
		Transformed df shape: (14, 20)
	Shifting data from column 3(workplace_address)
	page 4...
		Current number of columns: 23 23
		23, 23
		Keeping page 1 columns
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
		Current number of columns: 22 23
		23, 23
		Dropping columns

	**Fixing column parsing for page 5 of F22-1445 Records_Part6.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part6.pdf...
		Original df shape:  (35, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_closed',
       'unknown_closure_type', 'open', 'days_since_last_case',
       'active_clusters'],
      dtype='object')
		Transformed df shape: (14, 22)
	Shifting data from column 3(workplace_address)
	page 6...
		Current number of columns: 23 23
		23, 23
		Keeping page 1 columns
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)

	Done
Columns unique to partF22-1445 Records_Part5.pdf: {'cluster_closed_epidate', 'blank1'}
Columns unique to partF22-1445 Records_Part6.pdf: none

In [846]:
dfs12[~dfs12['blank0'].isna()]

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,blank0,blank1,file
128,817.0,NHA,None,None,None,None,Unknown,10/8/2021,None,None,...,No,None,Unknown,No,No,None,Yes,40-2021,NaN,F22-1445 Records_Part5.pdf
129,817.0,NHA,None,None,None,None,Unknown,10/8/2021,None,None,...,No,None,Unknown,No,No,None,Yes,40-2021,NaN,F22-1445 Records_Part5.pdf
29,30.0,FHA,None,None,DELTA,4/4/2021,4/16/2021,NaN,NaN,Restaurant/Ba\rr/Lounge,...,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN,F22-1445 Records_Part6.pdf
30,31.0,FHA,None,None,SURREY,4/4/2021,4/16/2021,NaN,NaN,Retail,...,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN,F22-1445 Records_Part6.pdf
31,32.0,FHA,None,None,SURREY,4/4/2021,4/10/2021,NaN,NaN,Office,...,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN,F22-1445 Records_Part6.pdf
32,33.0,VCH,None,None,North\rVancouver,4/4/2021,NaN,4/4/2021,5/15/2021,Maintenance/\rTrades/Constr\ruction,...,No,No,No,NaN,No,14-2021,NaN,16-2021,NaN,F22-1445 Records_Part6.pdf
41,30.0,FHA,None,None,DELTA,4/4/2021,4/16/2021,NaN,NaN,Restaurant/Ba\rr/Lounge,...,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN,F22-1445 Records_Part6.pdf
42,31.0,FHA,None,None,SURREY,4/4/2021,4/16/2021,NaN,NaN,Retail,...,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN,F22-1445 Records_Part6.pdf
43,32.0,FHA,None,None,SURREY,4/4/2021,4/10/2021,NaN,NaN,Office,...,No,No,Yes,NaN,No,14-2021,NaN,14-2021,NaN,F22-1445 Records_Part6.pdf
44,33.0,VCH,None,None,North\rVancouver,4/4/2021,NaN,4/4/2021,5/15/2021,Maintenance/\rTrades/Constr\ruction,...,No,No,No,NaN,No,14-2021,NaN,16-2021,NaN,F22-1445 Records_Part6.pdf

### Process all docs

In [847]:
n_docs = 7
filenames = [f'F22-1445 Records_Part{i}.pdf' for i in range(1,n_docs+1)]
dfs_all12, reference_all12 = parse_pdf(filenames, pages='all', filename='pdfs_parsed_to_df_list')

Extracting the following files:
F22-1445 Records_Part1.pdf
number of columns: 22
	page 1...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 2...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 3...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 4...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 5...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 6...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 7...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 8...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 9...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 10...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 3(workplace_address)
	page 11...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 11 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 12...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 13...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 13 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 14...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 15...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 16...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 17...
		Current number of columns: 22 22
		22, 22
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 18...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 19...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 19 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 20...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 21...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 22...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 22 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 23...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 24...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 24 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 25...
		Current number of columns: 22 22
		22, 22
		Keeping page 1 columns
	Attempting to consolidate rows that were incorrectly split:
	Removing duplicate rows from F22-1445 Records_Part1.pdf...
		Original df shape:  (14, 22)
		Original columns: Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate'],
      dtype='object')
		Transformed df shape: (13, 22)
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 26...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 27...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 28...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 29...
		Current number of columns: 22 22
		22, 22
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 30...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 30 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 31...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 31 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 32...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 32 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 33...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 33 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 34...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 34 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 35...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 35 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 36...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 36 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 37...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 37 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 38...
		Current number of columns: 24 22
		22, 22
		Padding columns

	**Fixing column parsing for page 38 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0', 'blank1'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 39...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 39 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 40...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 40 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 41...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 41 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 2
	Shifting data from column 2(workplace_name)
	Shifting data from column 3(workplace_address)
	page 42...
		Current number of columns: 23 22
		22, 22
		Padding columns

	**Fixing column parsing for page 42 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',
       'workplace_classification', 'cases_when_cluster_confirmed',
       'total_cases', 'workplace_status', 'closure_y_n', 'closed_by_order',
       'voluntary_closure', 'closure_date', 'partially_cosed', 'open',
       'days_since_last_case', 'cluster_confirmed_epidate',
       'cluster_closed_epidate', 'blank0'],
      dtype='object')
	Removing s.22(1) from column 3
	Shifting data from column 3(workplace_address)
	page 43...
		Current number of columns: 24 22
		22, 22
		Padding columns

	**Fixing column parsing for page 43 of F22-1445 Records_Part1.pdf**
		Index(['Unnamed: 0', 'HA', 'workplace_name', 'workplace_address', 'city',
       'date_cluster_confirmed_public_health', 'date_cluster_no_longer_active',
       'earliest_reported_cases', 'latest_reported_cases',

In [848]:
reference_all12

{'corrected pages': {'F22-1445 Records_Part1.pdf': 124,
  'F22-1445 Records_Part2.pdf': 139,
  'F22-1445 Records_Part3.pdf': 136,
  'F22-1445 Records_Part4.pdf': 123,
  'F22-1445 Records_Part5.pdf': 86,
  'F22-1445 Records_Part6.pdf': 109,
  'F22-1445 Records_Part7.pdf': 81},
 'unique columns': {'F22-1445 Records_Part7.pdf': 'none'}}

In [849]:
dfs12

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,blank0,blank1,file
0,753.0,VIHA,None,None,Victoria,9/8/2021,NaN,8/5/2021,9/8/2021,Restaurant/Bar/\rLounge,...,Unknown,No,Yes,34.0,No,36-2021,NaN,NaN,NaN,F22-1445 Records_Part5.pdf
1,754.0,VIHA,None,None,Nanaimo,9/8/2021,NaN,8/31/2021,9/8/2021,Manufacturing/I\rndustry,...,Unknown,No,Yes,34.0,No,36-2021,NaN,NaN,NaN,F22-1445 Records_Part5.pdf
2,755.0,VIHA,None,None,ake Cowichan,9/8/2021,NaN,9/6/2021,9/8/2021,Restaurant/Bar/\rLounge,...,Unknown,No,Yes,34.0,No,36-2021,NaN,NaN,NaN,F22-1445 Records_Part5.pdf
3,756.0,NHA,None,None,Unknown,9/8/2021,9/23/2021,NaN,NaN,Manufacturing/I\rndustry,...,Unknown,No,No,NaN,No,36-2021,36-2021,NaN,NaN,F22-1445 Records_Part5.pdf
4,757.0,NHA,None,None,Unknown,9/8/2021,9/21/2021,NaN,NaN,School/Daycare,...,Unknown,No,No,NaN,No,36-2021,NaN,NaN,NaN,F22-1445 Records_Part5.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,92.0,NHA,None,None,nknown,4/7/2021,6/9/2021,NaN,NaN,Manufacturin\rg/Industry,...,Unknown,No,No,NaN,No,14-2021,NaN,NaN,NaN,F22-1445 Records_Part6.pdf
156,93.0,FHA,None,None,ORT\rOODY,4/8/2021,6/17/2021,NaN,NaN,Gym/Fitness,...,No,No,Yes,NaN,No,14-2021,NaN,NaN,NaN,F22-1445 Records_Part6.pdf
157,94.0,FHA,None,None,URREY,4/8/2021,5/15/2021,NaN,NaN,Gym/Fitness,...,No,No,Yes,NaN,No,14-2021,NaN,NaN,NaN,F22-1445 Records_Part6.pdf
158,95.0,FHA,None,None,URNABY,4/8/2021,5/11/2021,NaN,NaN,Gym/Fitness,...,No,No,Yes,NaN,No,14-2021,NaN,NaN,NaN,F22-1445 Records_Part6.pdf
159,96.0,FHA,None,None,URREY,4/8/2021,4/29/2021,NaN,NaN,Office,...,Yes,No,Yes,NaN,No,14-2021,NaN,NaN,NaN,F22-1445 Records_Part6.pdf

### Save CSV or parsed data before processing

In [895]:
filename='pdfs_parsed_2023-03-27'
path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'

In [896]:
save_csv(dfs12, filename=filename, path=path)

File saved:  C:/Users/silvh/OneDrive/lighthouse/portfolio-projects/BC-Covid-workplace-closures/data/interim/pdfs_parsed_2023-03-27.csv
Time completed: 2023-03-27 03:37:00.282614

In [12]:
save_csv(pd.concat(dfs12), filename=filename, path=path)

File saved:  C:/Users/silvh/OneDrive/lighthouse/portfolio-projects/BC-Covid-workplace-closures/data/interim/pdfs_parsed_to_df_list.csv
Time completed: 2023-03-27 03:49:32.233744

# Load files

In [4]:
filename='pdfs_parsed_to_df_list'
path=r'C:\Users\silvh\OneDrive\lighthouse\portfolio-projects\BC-Covid-workplace-closures\data\interim'
dfs12 = loadpickle(filename+'.sav', path)

Time completed: 2023-03-27 03:45:38.371763

In [9]:
len(dfs12)

7

In [11]:
pd.concat(dfs12)

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,open,days_since_last_case,cluster_confirmed_epidate,cluster_closed_epidate,blank0,blank1,blank2,file,active_clusters,unknown_closure_type
0,1,FHA,None,None,SURREY,4/1/2021,4/17/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,No,NaN,13-2021,NaN,NaN,NaN,NaN,F22-1445 Records_Part1.pdf,NaN,NaN
1,2,FHA,None,None,LANGLEY,4/1/2021,4/13/2021,NaN,NaN,Other,...,No,NaN,13-2021,NaN,NaN,NaN,NaN,F22-1445 Records_Part1.pdf,NaN,NaN
2,3,FHA,None,None,SURREY,4/1/2021,4/13/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,No,NaN,13-2021,14-2021,NaN,NaN,NaN,F22-1445 Records_Part1.pdf,NaN,NaN
3,4,FHA,None,None,BURNABY,4/1/2021,4/21/2021,NaN,NaN,Gym/Fitness,...,No,NaN,13-2021,14-2021,NaN,NaN,NaN,F22-1445 Records_Part1.pdf,NaN,NaN
4,5,FHA,None,None,BURNABY,4/1/2021,4/14/2021,NaN,NaN,Restaurant/Bar/L\rounge,...,No,NaN,13-2021,14-2021,NaN,NaN,NaN,F22-1445 Records_Part1.pdf,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2799,1092.0,IHA,NaN,Revelstoke,1/28/2022,NaN,1/28/2022,NaN,School/Daycare,5,...,NaN,No,2-2022,NaN,NaN,NaN,NaN,F22-1445 Records_Part7.pdf,4-2022,No
2800,1093.0,IHA,NaN,None,260 Cedar Ave,NaN,1/31/2022,NaN,1/31/2022,None,...,No,No,No,5-2022,NaN,NaN,NaN,F22-1445 Records_Part7.pdf,None,No
2801,1094.0,IHA,NaN,None,Road,NaN,1/31/2022,NaN,1/31/2022,None,...,No,No,No,5-2022,NaN,NaN,NaN,F22-1445 Records_Part7.pdf,None,No
2802,1093.0,IHA,NaN,None,260 Cedar Ave,NaN,1/31/2022,NaN,1/31/2022,None,...,No,No,No,5-2022,NaN,NaN,NaN,F22-1445 Records_Part7.pdf,None,No
2803,1094.0,IHA,NaN,None,Road,NaN,1/31/2022,NaN,1/31/2022,None,...,No,No,No,5-2022,NaN,NaN,NaN,F22-1445 Records_Part7.pdf,None,No

In [893]:
def clean_df(raw_df):
    raw_df = raw_df.transpose().apply(lambda x: x.str.replace('\r', '')).transpose()
    raw_df = raw_df.transpose().apply(lambda x: x.str.lower()).transpose()
    # raw_df.fillna('', inplace=True)
    # raw_df = raw_df.transpose().apply(lambda x: x.str.replace('', None)).transpose()
    # raw_df.fillna(None)
    return raw_df

cleaned = clean_df(dfs12.head())
cleaned

,index,HA,workplace_name,workplace_address,city,date_cluster_confirmed_public_health,date_cluster_no_longer_active,earliest_reported_cases,latest_reported_cases,workplace_classification,...,partially_closed,unknown_closure_type,open,days_since_last_case,active_clusters,cluster_confirmed_epidate,cluster_closed_epidate,blank0,blank1,file
0,NaN,viha,None,None,victoria,9/8/2021,NaN,8/5/2021,9/8/2021,restaurant/bar/lounge,...,unknown,no,yes,NaN,no,36-2021,NaN,NaN,NaN,f22-1445 records_part5.pdf
1,NaN,viha,None,None,nanaimo,9/8/2021,NaN,8/31/2021,9/8/2021,manufacturing/industry,...,unknown,no,yes,NaN,no,36-2021,NaN,NaN,NaN,f22-1445 records_part5.pdf
2,NaN,viha,None,None,ake cowichan,9/8/2021,NaN,9/6/2021,9/8/2021,restaurant/bar/lounge,...,unknown,no,yes,NaN,no,36-2021,NaN,NaN,NaN,f22-1445 records_part5.pdf
3,NaN,nha,None,None,unknown,9/8/2021,9/23/2021,NaN,NaN,manufacturing/industry,...,unknown,no,no,NaN,no,36-2021,36-2021,NaN,NaN,f22-1445 records_part5.pdf
4,NaN,nha,None,None,unknown,9/8/2021,9/21/2021,NaN,NaN,school/daycare,...,unknown,no,no,NaN,no,36-2021,NaN,NaN,NaN,f22-1445 records_part5.pdf

In [894]:
clean_df(dfs12)['city'].unique()

array(['victoria', 'nanaimo', 'ake cowichan', 'unknown', 'castlegar',
       'kamloops', 'kelowna', 'crofton', 'parksville', 'vancouver',
       'princeton', 'tofino', 'vernon', 'angley', 'duncan', 'salmon arm',
       'cranbrook', 'illiams lake', 'ancouver', 'icamous', 'evelstoke',
       'bbotsford', 'itt meadows', 'hilliwack', 'enticton', 'rmstrong',
       'elowna', 'squimalt', 'obble hill', 'ictoria', 'nknown',
       'est kelowna', 'cawston', 'okanagan falls', 'courtenay',
       'comox- strathcona d', 'burnaby', 'port alberni', 'abbotsford',
       'williams lake', 'langford', None, 'delta', 'surrey', 'm',
       'langley', 'pittmeadows', 'northvancouver', 'portcoquitlam',
       'ridge', 'ord', 'powellriver', 'moody', 'ster', 's', 'elta',
       'ortoquitla', 'urnaby', 'estancouver', 'orthancouver', 'ortoody',
       'urrey'], dtype=object)

# *End of Page*